### ISSUE TITLE
Materialized View & Migration

### ISSUE THREAD

**Issue by dalemayehu** [jeremyevans/sequel#1000]
Is there a recommended way to create a migration script for materialized views? 

Currently using `create_view` in a migration script works as expected except for the schema dump. Nothing about the view creation is dumped into the schema file. I suppose that is intentional since doing so will probably result in a migration script that cannot be used with a different database. But that also makes it very painful/impossible to write unit tests for the new view even when one does not have such portability requirements.

**Comment by jeremyevans** [comment]
The schema dumper does not currently support views, materialized or otherwise.  There aren't currently any plans to add the feature, mainly because none of the database adapters support dumping views.

This should not affect testing unless you are using the output of the schema dumper to create the test database.  If you are doing that, stop, it is a bad practice.  Migrate your test databases like you migrate your development and production databases.  If you feel you must use a schema dump of the development/production database to create the test database, you should use the database's tools, not Sequel's.
