### ISSUE TITLE
List Plugin :move_up / :move_down methods. Why raise "Sequel::Error" on out-of-bounds?

### ISSUE THREAD

**Issue by kematzy** [jeremyevans/sequel#1003]
Hi,

I'm just curious why the `:move_down` & `:move_up` methods of the List plugin raises an "Sequel::Error" when going out of bounds?

What is the smart intention I don't get?

I my mind the "least surprise" principle would be to just set max / min positions and move to that position instead of throwing an error. A bit like this (quick example hack):

    def move_up(n = 1)
      min_pos = position_value - n
      min_pos = 1 if min_pos < 1
      move_to(min_pos) 
    end
    # the above would be better handled in the `:move_to` method

When moving an item up or down a list, it may not be fully known if we have already hit the min/max position. Or is there some smarter way to code which I cannot see atm?

Thanks for your time.

**Comment by jeremyevans** [comment]
I'm not sure the specific reasoning why `move_down` and `move_up` raise exceptions for out of bounds.  The list plugin wasn't written by me, it was taken from an external source.  However, one possible reason is it may make it simpler to catch unintentional errors.  But it seems friendly to me to just handle this automatically.

Since this currently raises an exception, I don't think we'd be breaking backwards compatibility to change it to use the first or last position.  I'll try to make that change today.

**Comment by kematzy** [comment]
Wow! You are just amazing.  One hour turnaround time for this issue from being raised to fixed and closed. Thanks a lot!
