### ISSUE TITLE
virtual_row with if modifier in block

### ISSUE THREAD

**Issue by redsnow1992** [jeremyevans/sequel#1015]
In one application, I want to filter according to parameters' presence as the following:
```ruby
DB[:item].where{
    Sequel.like(name, "%params[:name]%") if params[:name].present?
    rank =~ 1 if params[:rank].present?
}
=> #<Sequel::Mysql2::Dataset: "SELECT * FROM `tb_item` WHERE (`rank` = 1)">
```
but when I use the following code, the `rank` part is gone:
```ruby
DB[:item].where{|item|
    Sequel.like(item.name, "%params[:name]%") if params[:name].present?
    item.rank =~ 1 if params[:rank].present?
}
=> #<Sequel::Mysql2::Dataset: "SELECT * FROM `tb_item`">
```
should the above two piece of codes behave differently?

**Comment by jeremyevans** [comment]
I don't think your code examples will do what you want.  The `Sequel.like` code is going to get ignored, even if `params[:name]` is present.  Additionally, you aren't doing interpolation inside the second argument to `Sequel.like`.  I think the reason for the difference in behavior is because `params` in the first example is going to return a `Sequel::SQL::Identifier` instance, it's not going to call the params method in the surrounding scope.

You should probably switch to:

```ruby
ds = DB[:item]
ds = ds.where(Sequel.like(name, "%#{ds.escape_like(params[:name])}%")) if params[:name].present?
ds = ds.where(:rank=>1) if params[:rank].present?
```

In the future, note that as mentioned in the contribution guidelines, questions about how to use Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should only be used for reporting bugs in Sequel, not as a general help forum.
