### ISSUE TITLE
"WHERE IN array" producing wrong SQL

### ISSUE THREAD

**Issue by whamilton42** [jeremyevans/sequel#1025]
**Version 4.23.0**

This code:

```ruby
db = Sequel.connect(adapter: "postgres", database: "test")
db[:things].where(whatever: [])
```

Produces this SQL:

```sql
SELECT * FROM things WHERE ("whatever" != "whatever")
```

**Comment by jeremyevans** [comment]
That's the expected SQL, as it handles the case where `whatever` is NULL correctly (consider `where({:whatever=>[]}=>nil)`).  If you want it to just evaluate to a false condition, use the empty_array_ignore_nulls extension.

**Comment by whamilton42** [comment]
I think the problem is just that it scans the whole table for no reason, since it can never return a result. Ideally it would just return nothing. No idea how feasible that is within the gem though.

**Comment by jeremyevans** [comment]
It's trivial to make the change (see the source code for the empty_array_ignore_nulls extension).  It just doesn't handle NULL values correctly when the expression is used inside more complex expressions, which is why the faster behavior is not the default.

Ideally this is something that the database would optimize, using an index to find NULL values, and returning NULL for those and false for other values.  But I'm not sure which databases if any actually do that optimization.
