### ISSUE TITLE
Table names with double underscore can't be created/queried with a Symbol

### ISSUE THREAD

**Issue by elado** [jeremyevans/sequel#1037]
Table creation:

```ruby
# Symbol name -- error
> DB.create_table :hello__world
# => ERROR -- : PG::InvalidSchemaName: ERROR:  schema "hello" does not exist: CREATE TABLE "hello"."world" ()

# String name -- works
> DB.create_table "hello__world"
# => CREATE TABLE "hello__world" ()
```

Table model/query:

```ruby
# Symbol table name
class HelloWorld < Sequel::Model(:hello__world)
end

HelloWorld.all
# => ERROR -- : PG::UndefinedTable: ERROR:  relation "hello.world" does not exist


# String table name
class HelloWorld < Sequel::Model('hello__world')
end
# => Sequel::Error: Model.set_dataset takes one of the following classes as an argument: Symbol, LiteralString, SQL::Identifier, SQL::QualifiedIdentifier, SQL::AliasedExpression, Dataset

# Identifier table name -- works
class HelloWorld < Sequel::Model(Sequel.identifier('hello__world'))
end

HelloWorld.all
# => INFO -- SELECT * FROM "hello__world"
```

Can the `__` convention be turned off?

**Comment by jeremyevans** [comment]
It is possible to turn off the `__` convention, but it's a bad idea.  Instead, just call `Sequel.identifier` with the identifier you don't want to split.  I see you already know that, so I assume you want to know how to turn of the `__` conversion.  Here's how you do that:

```ruby
DB.extend_datasets(Module.new do
  def split_symbol(c)
    [nil, c.to_s, nil]
  end
end)
```

Note that this will also disable the `___` convention for aliasing.

Note that as mentioned in the contribution guidelines, questions like this about how to use Sequel should be asked on the sequel-talk Google Group or IRC.  You should only open an issue in GitHub Issues if you are sure it is due to an actual bug in the library.

**Comment by elado** [comment]
Thanks, Jeremy. I thought it was a bug.
