### ISSUE TITLE
PG::ConnectionBad: FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by gsdean** [jeremyevans/sequel#1046]
I'm this a lot. I'm running a standard PG instance on Heroku. This makes me think I'm handling connection pooling wrong.

I'm essentially doing: 
`Sequel.connect('connection_string', :max_connections => 3)`

Is there anything else to it?

**Comment by jeremyevans** [comment]
You are probably calling that per-request instead of once at startup, so you are creating a separate Database object with it's own connection pool for each request.  A reference to the Database object is kept in `Sequel::DATABASES` by default, so it never gets garbage collected.  In general, you should be creating a single Database object on process initialization.  The recommendation is to store that object in a constant named `DB`.

As mentioned in the contribution guidelines, questions on how to use Sequel should be asked on the sequel-talk Google Group or IRC.  A GitHub issue should only be created if you are sure it is a bug in Sequel itself.
