### ISSUE TITLE
Weird results on query

### ISSUE THREAD

**Issue by fotanus** [jeremyevans/sequel#1059]
Hi there,

I'm having some really weird results when doing some queries. Here is some lines:

```
> require 'sequel'
> conn = Sequel.connect 'postgres://localhost/bundler-api'
> conn[:versions].join(:rubygems, id: :rubygem_id).where(name: '12_hour_time').count
=> 0
 > conn["select count(*) from versions as v, rubygems as r where v.rubygem_id = r.id and r.name = '12_hour_time';"].to_a.count
 => 26852944 
```

And this is what I got from psql:

```
$ psql bundler-api
bundler-api=# select count(*) from versions as v, rubygems as r where v.rubygem_id = r.id and r.name = '12_hour_time';
 count 
-------
     3
(1 row)
```

I'm using this gems:
```
$ gem list | grep sequel
sequel (4.3.0)
sequel_pg (1.6.8)
```

Do you have any idea on what is going wrong here? I'll start to check the sequel code now to see if I can find something.

**Comment by jeremyevans** [comment]
Well, I don't understand why you are getting the large number.  The `dataset.to_a.count` should produce 1, since `Dataset#to_a` should produce a an array such as `[[:count, 3]]`  for that query.   You would want to use `.single_value` instead of `.to_a.count`, since the query returns a single value.

You could try updating to the latest versions of Sequel and sequel_pg, and you could also try without sequel_pg (set the NO_SEQUEL_PG environment variable).  Also, if you are using pg 0.18+, you must use sequel_pg 1.6.11+.

**Comment by fotanus** [comment]
Upgrading sequel_pg to 1.6.13 actually solve the issue, thanks!
