### ISSUE TITLE
Association Does Not Have Primary Key

### ISSUE THREAD

**Issue by hypernova2002** [jeremyevans/sequel#1061]
Hi,

I'm having some problems with one-to-one assocations. Sequel is returning the error, object does not have a primary key. I believe there is an issue in this line

https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/associations.rb#L2372

pk is an initialized variable, so this line will always raise an error

**Comment by jeremyevans** [comment]
`pk` isn't a local variable, so that will be call to the `Model#pk` method, which returns the primary key value for the object.  If the object does not have a primary key set, then you can't associate to it, which is why an exception is raised.  So that code is fine.

If you are having problems using Sequel, please ask for help on the sequel-talk Google Group or IRC.

**Comment by hypernova2002** [comment]
Yeah, you're right. I seem to have set the associations the wrong way around

**Comment by Aryk** [comment]
@jeremyevans - I actually came across the same issue.

So for a belongs_to/has_one, according to your [documentation](https://github.com/jeremyevans/sequel/blob/master/doc/active_record.rdoc#associations-1), belongs_to -> many_to_one and has_one -> one_to_one. However, if you are doing a 1-to-1 relationship, it seems strange to use many_to_one. If we want to stick with "one_to_one" as a method, in theory, it should work no matter which table has the foreign key. The nice thing about the active record naming is that didn't deal with the relationship on both sides of the coin, i.e. belongs_to, which can work for both has_many and has_one. I guess, it just makes it harder to reason about the relationship if you need to write many_to_one to explain what you are thinking in your head as a one_to_one...
