### ISSUE TITLE
Migration generators

### ISSUE THREAD

**Issue by maksimf** [jeremyevans/sequel#1068]
Hello there! I read a blog post about Sequel and became interested. I wonder, why sequel provide no generators for migrations? Is this a matter of ideology or just implementation?

**Comment by jeremyevans** [comment]
Nobody has written the code, and I don't consider it a high priority.  It's possible it could be committed in the future, but I'd like to see an external implementation with some community support first, that could be merged in.  A basic Sequel migration skeleton is just:

```ruby
Sequel.migration do
  up do
  end
  down do
  end
end
```

Because it is so simple to create by hand, I don't think there is a pressing need to built an automated tool for it.
