### ISSUE TITLE
sequel -C conversion converts MySQL text field to something that sqlite sees as a blob

### ISSUE THREAD

**Issue by dtenenba** [jeremyevans/sequel#1071]
Hi,

I have a MySQL database (called foo) I created like this:

    create table t1 (a text);
    insert into t1 (a) values ('hello');

Then I converted that database to sqlite using sequel:

     sequel mysql://root@localhost/foo -C sqlite://foo.sqlite3

Then looking at the resulting sqlite database, the column type of the 'a' column is correctly shown as text:

    sqlite> .sch
    CREATE TABLE `t1` (`a` text);

However, the underlying type of the row data is considered to be a blob:

    sqlite> SELECT typeof(a) FROM t1;
    blob

This causes problems for me because (as I've learned) SQLite does not type columns, it types individual values. My workflow is to take this sqlite database and read it into the R language, however when I do that, the values in the text column come back as raw bytes, not text, because SQLite is telling R that the underlying value is a blob. 

So, is this a bug in the conversion process? If so, can it be fixed?

Otherwise I will have to add an additional step to my workflow, inserted after the conversion, in which I read in the text column of each row and write it out again, causing its underlying type to be changed from text to blob.

Thanks.

**Comment by jeremyevans** [comment]
I believe this is because MySQL stores blobs the same as text, using the same type id (249-252 depending on the size of the type).  If you don't have any blob fields in MySQL, you may be able to switch to using the mysql2 adapter.  If you must continue using the mysql adapter, you could try removing the default conversion procs for blob/text types:

```ruby
(249..252).each{|i| DB.conversion_procs.delete(i)}
```

To more directly answer your question, I believe this is a bug, but a bug in MySQL.  It should store text types differently than blob types using different type ids, so that software that retrieves values can differentiate between the two.  If there is a way to differentiate between the two using ruby-mysql and Sequel isn't using it, please let me know how to do so and I'll look into it.

**Comment by dtenenba** [comment]
Switching to mysql2 did the trick! BTW, I had to `gem install mysql2` even though the 
[mysql2 readme](https://github.com/brianmario/mysql2#sequel) suggests that I should not have to with Sequel. Anyway, that's not really relevant. Thanks for the help!
