### ISSUE TITLE
raising Sequel::Rollback in after_create_hook results in "persisted" object

### ISSUE THREAD

**Issue by mrbrdo** [jeremyevans/sequel#1076]
```ruby
resource.after_create_hook { fail Sequel::Rollback }
resource.save # => nil
resource.persisted? # => true
resource.id # => some integer
```
but in fact, the record is not present in the DB, since the transaction was rolled back

**Comment by jeremyevans** [comment]
This is expected behavior.  The object was persisted, but sometime after the save it was deleted/rolled back.  You'd get the same results if you did:

```ruby
resource.save
resource.this.delete
resource.persisted?
resource.id
```

If you want to see if the object actually exists in the database, use `exists?` instead of `persisted?`.

**Comment by mrbrdo** [comment]
Well technically it was never persisted, as the save transaction was rolled back as part of the save itself. So from the perspective of the user and the DB it was never persisted.

**Comment by jeremyevans** [comment]
Technically, it was persisted (the `INSERT` was successful), and later it was deleted/rolled back.  Consider what `persisted?` should return in the following code:

```ruby
DB.transaction do
  resource.save
  resource.persisted?
  raise Sequel::Rollback
end
```

The `persisted?` method is not a base model method, it is added by the active_model plugin solely for compatibility.  The logic that the active_model plugin uses (`!new? && @destroyed != true`) is designed to be similar to the logic that ActiveRecord uses (`!(new_record? || destroyed?)`).

**Comment by mrbrdo** [comment]
Well at the point of placement of `persisted?` in your snippet there is no ambiguity about the result. The ambiguity is after the rollback.
If the goal of this method was to achieve similar behavior to ActiveRecord, then it is not working correctly, since ActiveRecord will return false in this case (I would also argue this makes more sense than the current behavior, as I would not consider a rolled-back transaction as persisted).

**Comment by jeremyevans** [comment]
To have `resource.persisted?` operate differently depending on whether the transaction was rolled back would require that transactions keep track of model instances, which Sequel does not do.  I think the following might work for your use case:

```ruby
  class Resource < Sequel::Model
    def after_create
      db.after_rollback{@destroyed = true}
      super
    end
  end
```

It's possible we could add a plugin for such behavior, but I'm against doing it by default for performance/memory reasons (think creating a large number of objects inside a transaction).

**Comment by mrbrdo** [comment]
Looks like a reasonable solution. Would this also reset the id to nil?
It would be nice to have this as an official plugin for those who want to match AR behavior in this case.
What would be the performance penalty in the case you are referring to? The creation of the instance variable or?

**Comment by jeremyevans** [comment]
I don't think it should reset the primary key to nil, just mark the object as destroyed, since that reflects what happened (a rollback of an insert is basically a delete). It's possible that could be an option in the plugin, though the semantics get tricky for non-autoincrementing primary keys.  In general, I prefer to keep things simple, and as this doesn't appear to be a common need, I'm resistant to adding more complexity. I'm not interested in matching AR bug-for-bug, whackamole is not my idea of fun.

The performance penalty is that using after_rollback with a block keeps the object in memory until the transaction commits, which for large numbers of objects can be a large amount of memory.

**Comment by mrbrdo** [comment]
Well I would imagine that that penalty would be avoided if it was a default (since you mention this is the reason not to make it default).
I'm not sure keeping the primary key is a good idea, as I would imagine the same primary key will get used for the next saved record in this table, and this could be a problem if the id of this *non-persisted* record gets used to update something in the database. Also if this was implemented as a plugin to provide the option of similar behavior as with AR, then it makes sense to follow this part too.

Example of use case (and how we discovered this "issue"): https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L19 (arguably poor code but none-the-less)

**Comment by jeremyevans** [comment]
In terms of autoincrementing primary key reuse, it depends on the database.  Sequence based databases such as PostgreSQL and Oracle will definitely not reuse primary keys.  MySQL won't either, but SQLite will.  You definitely can't rely on the same primary key being used, though, on any SQL database, if there are any transactions running concurrently.

The penalty would not be avoided if this behavior was the default.  If you tie model instance behavior to transaction commit/rollback, the transaction needs to keep a reference to the model until then.  Using after_commit/after_rollback causes possible performance/memory issues whenever a transaction deals with a large number of records.

As I mentioned, I'm not interested in matching AR for the sake of compatibility.  If you would like to recommend possible features, recommend such features on their own merits, not because AR operates that way.

This proposed plugin would not be added for AR compatibility, but because some users may want rolled back instances to be considered as not persisted.

As for setting the autoincrementing primary key field to nil, I don't think it's a good idea in all code.  There are plenty of cases where you may want to know the primary key used for a rolled back record, and setting the primary key to nil would make that more difficult.  Certainly I don't think the autoincrementing primary key field should be set to nil by default.  Possibly, it could be an option, but as I mentioned, it gets more complex as not all primary keys are autoincrementing.

**Comment by mrbrdo** [comment]
Ok, like I said the plugin would be a good option.
I am not really proposing this because of AR compatibility, it just makes more sense to me. If I save a record and it fails I don't expect the record to have an id and say it's persisted (also I would not expect a record that is not persisted to have an ID). I understand how it could make sense at a lower level but not when just calling save and then doing something with the model.

**Comment by jeremyevans** [comment]
I would argue that save succeeds, and the record is deleted/rolled ack after the save.  Certainly if you have a transaction wrapping the save, that's definitely what happens.  For an internal transaction to save, it's less obvious, but I'd say the same idea applies.  `save` may have failed, but the object was definitely persisted and then deleted.  You can't say it was never persisted, because inside after_save/after_create, `persisted?` would obviously be true up until the point of rollback.

Anyway, I agree that such a plugin would be useful, and I'll try to implement it before the next release.

**Comment by mrbrdo** [comment]
Thanks, sounds good. I guess the most logical thing would be that `persisted?` is true in after_create as you say, but is false in after_rollback. So then the plugin's after_rollback should be as soon in the "chain" (inheritance) as possible. Although I'm not sure if you can do much about *where* it is, perhaps a note in the documentation.

**Comment by jeremyevans** [comment]
After looking at the code, the `@destroyed` flag is specific to the `active_model` plugin, so this doesn't make sense as a plugin, unless we wanted that plugin to depend on `active_model`.  I'm just going to modify the `active_model` plugin to use after_rollback.  People who don't want the performance/memory issues can just not use `active_model` plugin.

**Comment by mrbrdo** [comment]
To be honest this makes a lot of sense, since code that works with ActiveModels would likely make assumptions based on ActiveRecord behavior anyway.
Thanks.
