### ISSUE TITLE
Does sequel respect deferrable constraints within a transaction?

### ISSUE THREAD

**Issue by bwiggs** [jeremyevans/sequel#1077]
I've created a deferrable constraint on a table column in my postgres database. When I try to modify rows in a transaction, sequel throws an error due to that constraint. I would expect the constraint not to fire until the end of the transaction. Is this expected?

**Comment by jeremyevans** [comment]
if your database is raising a constraint violation error on INSERT/UPDATE instead of on COMMIT, this really a database issue, not a Sequel issue. If you have a deferrable constraint that is initially deferred, the database shouldn't raise an error until COMMIT.

So this doesn't sound like a bug in Sequel itself.  If you are still having problems after verifying that your constraint is both deferrable and initially deferred, please post a self contained example on sequel-talk and we can troubleshoot the problem there.
