### ISSUE TITLE
Question about PG Interval extension

### ISSUE THREAD

**Issue by b-wojtowicz** [jeremyevans/sequel#1080]
Hello there!

I noticed that pg_interval ext uses ActiveSupport:
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_interval.rb

I was wondering if you plan to drop it in the future to remove ActiveSupport dependency? :)

Best Regards
Bart

**Comment by jeremyevans** [comment]
At the time, there was not a good class for storing intervals/durations other than `ActiveSupport::Duration`.  I'm not sure how much has changed since then.  There is `ruby-duration`, but that appears to have a runtime dependency on `active_support`, so switching to that wouldn't make sense if the goal is to avoid `active_support`.

As mentioned in the contribution guidelines, questions like this should be asked on the sequel-talk Google Group.  You should only open up a GitHub issue if you are sure what you are reporting is a bug in the library.
