### ISSUE TITLE
In sequel-4.27.0 Sequel.synchronize raise ThreadError: deadlock; recursive locking

### ISSUE THREAD

**Issue by tmtm** [jeremyevans/sequel#1084]
Sequel 4.26:
```
% ./sequel-4.26.0/bin/sequel mysql2://localhost/test -c 'Sequel.synchronize{ p DB[:t].all }'
[{:id=>"a"}]
```

Sequel 4.27:
```
% ./sequel-4.27.0/bin/sequel mysql2://localhost/test -c 'Sequel.synchronize{ p DB[:t].all }'
Error: ThreadError: deadlock; recursive locking
/var/lib/gems/2.1.0/gems/sequel-4.27.0/bin/sequel:236:in `eval'
```

**Comment by jeremyevans** [comment]
This is expected.  You shouldn't be calling `Sequel.synchronize` around an expensive operation like that, it should only be used to protect access to a data structure that can be accessed by multiple threads simultaneously.  Note that on Sequel <4.27, that code would still be broken on JRuby or Rubinius.

If you really want this to work, override `Sequel.synchronize` to use a monitor instead of a mutex.
