### ISSUE TITLE
Dataset#eager_graph with additional conditions

### ISSUE THREAD

**Issue by mrbrdo** [jeremyevans/sequel#1090]
Is it possible to provide additional join conditions to Dataset#eager_graph? Was not able to find a way, as a temporary solution I ended up removing the join from opts[:join] and replacing it with my own.
PS: I will try `ds.eager_graph(:association=>proc{|ds| ... })` and see if that works for this case.

On a related note, if I called eager_graph after already doing a join on some other table, eager_graph changed the FROM clause to `FROM (subquery)`. I guess I understand how this would make sense in the generic case, but it's not what I wanted, because I actually want to refer to that joined table in the left join conditions for eager_graph. Is there a nice way of doing this? For now I just called eager_graph before doing the other joins, and then I changed the order in opts[:join] (since I am referring to the other table in the join conditions).

And finally, since I'm here anyway, is there a nicer way to add a "graph" alias than scope.opts[:graph][:column_aliases][:something] = [:table, :something]?

Thanks

**Comment by jeremyevans** [comment]
You cannot currently provide additional join conditions on a per-call basis when eager graphing, the API doesn't support it.  The best you can do is a eager_graph callback, as you mentioned.

The automatic use of from_self is expected and by design.  If that isn't what you want, you should probably use a custom query instead of using eager_graph.

You can set add_graph_aliases/set_graph_aliases to set up custom graph aliases.

**Comment by odigity** [comment]
@mrbrdo For future reference, Jeremy prefers if issues are only opened for confirmed bugs.

You can ask questions on the #sequel IRC channel or sequel-talk google group:

https://groups.google.com/forum/#!forum/sequel-talk

(Response times tend to be good.)

**Comment by mrbrdo** [comment]
Thanks.

One more thing regarding using a custom query instead of eager_graph for this case, is there an easy way to make sequel then automatically process the rows and set up the associated models (like eager_graph does)? I guess add_graph_aliases would be one part of that?

**Comment by jeremyevans** [comment]
You can use `Model#load` to create instances based on hashes, and autopopulate the `associations` cache for each instance based on the records associated.  That may not be easy, but it shouldn't be too difficult.

**Comment by mrbrdo** [comment]
Sounds good, thank you.
Do you think adding an option to pass conditions into eager_graph would make sense at some point? I would imagine it would not be a huge deal to implement since conditions from the association itself already get applied.
The reasoning being that one of the use cases for eager_graph is to be able to filter the records, I think it would make sense to have this option as well.

**Comment by jeremyevans** [comment]
Well, nobody else has asked for it yet, and I can't think of a good, backwards compatible API that would support it.  I'm certainly willing to consider patches.

From what you described, filtering employees using an eager_graph callback should work fine, since the filter conditions for employees are unlikely to vary per company.  Also, it seems like regular eager loading would work for the same thing think, if you use an eager callback.

**Comment by mrbrdo** [comment]
That's true although:
1. It produces `FROM subquery`, not sure if I do want that (what is the performance of that, comparable?)
2. Because of the above you cannot reference other tables in the callback (which is the real issue for me in this case)

I was able to work around it not too badly so I'm not in dire need of this feature but I don't like the code too much since it's a bit hacky. I remove the join from opts[:join] and add my own Sequel::SQL::JoinOnClause (I can't use #join since it will complain the alias is already in use). It's not the solution you proposed but it allows to achieve the result in just a few lines of code. Don't like it too much though.
