### ISSUE TITLE
paged_each for mysql2 does not allow querying the DB inside the loop

### ISSUE THREAD

**Issue by hnatt** [jeremyevans/sequel#1096]
I'm trying to process a large dataset with `.paged_each`, and it appears that in case of mysql2 adapter, once you are inside the loop, you can't query the database again. Example:

```ruby
> db[:users].paged_each { |user| db[:users].first(id: user[:id]) }
Sequel::DatabaseDisconnectError: Mysql2::Error: Lost connection to MySQL server during query
from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/mysql2.rb:88:in `each'
```

Querying any other table causes the same exception. The DB log is:

```
  INFO -- : (0.000115s) SET @@wait_timeout = 2147483
  INFO -- : (0.000094s) SET SQL_AUTO_IS_NULL=0
  INFO -- : (0.001254s) SELECT * FROM `users`
 ERROR -- : Mysql2::Error: Commands out of sync; you can't run this command now: SELECT * FROM `users` WHERE (`id` = 10) LIMIT 1
```

`pg` adapter does not suffer from this problem.

My `mysql2` gem version is 0.4.1.

I understand this is related to the fact that mysql2 adapter does not respect `:strategy` parameter for paged_each, always using streaming. But if it imposes such a drawback, I would like to have an option to use `:offset` or `:filter` srategy.

**Comment by jeremyevans** [comment]
I don't think this is related to paged_each.  In general in Sequel, you can't issue queries on the same connection inside Dataset#each.  There are adapters where that works, but it should never be relied on.  In short, the following type of code unsupported even in the cases where it works:

```
DB[:t1].each do |r|
  DB[:t2].where(:id=>r[:t1_id]).update(...)
end
```

The simplest fix is to use Dataset#all instead of Dataset#each.  However, if you must use Dataset#each, the easiest workaround if you are using the standard connection pool is to issue queries inside the Dataset#each block in a separate thread.  Another way is to use the sharded connection pool, setup a shard with the same connection info as the :default connection, and use that shard inside the Dataset#each block (xor issue the Dataset#each call on that shard).

**Comment by hnatt** [comment]
Thanks for your quick response and suggested workarounds!
