### ISSUE TITLE
Encoding::CompatibilityError error with binary fields with mysql2

### ISSUE THREAD

**Issue by pampa** [jeremyevans/sequel#1120]
I'm getting a seemingly random sequel-4.29.0/lib/sequel/adapters/mysql2.rb:200:in `literal_string_append': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError) exception when using a model for a table that has two binary(32) columns with mysql2 adapter. 

Only half of the rows are affected, and the error goes away if i drop the second binary column from the table.

code to reproduce the error:
```ruby
require 'sequel'

$db = Sequel.connect({'adapter'  => 'mysql2',
                      'database' => 'test',
                      'username' => 'root',
                      'host'     => 'localhost',
                      'charset'  => 'utf8'})
$db.run "drop table if exists my_blobs"
$db.run "CREATE TABLE `my_blobs` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `obj1` binary(32) NOT NULL,
      `obj2` binary(32) NOT NULL,
      `flip` bool       NOT NULL default 0,
        UNIQUE KEY `id` (`id`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8"

fh = open('/dev/urandom', 'rb')

10000.times do
  $db[:my_blobs] << { :obj1 => Sequel.blob(fh.read(32)), :obj2 => Sequel.blob(fh.read(32)) }
end

class MyBlob < Sequel::Model
end

MyBlob.each do |b|
  begin 
    b.flip = 1
    b.save
    puts "ok #{b.id}"
  rescue Encoding::CompatibilityError
    puts "er #{b.id}"
  end
end
```

**Comment by pampa** [comment]
Upon further investigation i found out that the error is triggered only if any of the two blobs contain one or more of the following bytes ["\x27","\x22","\n","\r","\x5c","\x00","\x1a"]

**Comment by jeremyevans** [comment]
I don't think this is a bug in Sequel.   Ruby doesn't allow mixing encodings in strings.  You need to use bound variables if the encodings are incompatible.  Try using the prepared_statements plugin, it will automatically use prepared statements for Model#save calls.

As to why the encodings are incompatible in this case, I'm not sure.  It could be mysql2 is returning one of the blobs as UTF8 and the other as binary, instead of returning both as binary.  If so, that's a bug in mysql2.

Can you do:

```ruby
MyBlob.each do |b|
  begin 
    b.flip = 1
    if b.obj1.encoding != b.obj2.encoding
      puts "incompatible encodings: obj1: #{b.obj1.encoding}, obj2: #{b.obj2.encoding}"
    end
    b.save
    puts "ok #{b.id}"
  rescue Encoding::CompatibilityError
    puts "er #{b.id}"
  end
end
```

If it prints that incompatible encodings warning, then the bug is that mysql2 is not always returning blobs with the same encoding.
