### ISSUE TITLE
Postgres problem

### ISSUE THREAD

**Issue by federicolucca** [jeremyevans/sequel#1123]
Hi all,

I have a problem on sequel with postgresql. Sometimes,not always, the connection goes in timeout. I saw the extension for resolve the problem,but after the add of the extension.
Sequel::Model.db.extension(:connection_validator)
Sequel::Model.db.pool.connection_validation_timeout = -1

like this code in database.rb,and restart apache .
I have the problem "socket closed" on every connections

Please help me
Federico

**Comment by federicolucca** [comment]
These exceptions

Sequel::DatabaseDisconnectError - PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly

Sequel::DatabaseConnectionError - PG::ConnectionBad: timeout expired

**Comment by jeremyevans** [comment]
The connection_validator extension can only help if the connection is already invalid when the pool checks it out.  If the connection becomes invalid while the connection is checked out, it can't handle that case (nothing can, really).

These exceptions you are getting are not related to Sequel, they come from the underlying connection to PostgreSQL, you need to troubleshoot that and fix things so that the server is not closing the connection.

**Comment by sabsowitz** [comment]
I'm having this issue due to me entering the wrong hostname. I need to get `gitrob configure` to run through the config again. Is it possible to do this, or is there a file that I can edit the hostname?

**Comment by Noxbag** [comment]
If you entered the wrong information or whatever, the configuration file is created in the current users home directory. So:

rm -f ~/gitrobrc

You can then re-run the configuration. Have fun! :)

**Comment by art-solopov** [comment]
Just in case someone else sees this: I've encountered a similar problem with Rails/Spring, Sequel and dry-container (without rails-sequel).
The gist of it is, don't let your Rake-tasks share the same connection as your main app. I made the Rake-task initialize its own connection (as recommended in the migration guide), and it all went swimmingly.
