### ISSUE TITLE
pg_array parsing issue

### ISSUE THREAD

**Issue by twillis** [jeremyevans/sequel#1131]
I came across some data in a production db that was represented in psql as...

[0:0]={26e0d9a5-00ee-4a76-8418-86ec61c942b0}

rather than

{26e0d9a5-00ee-4a76-8418-86ec61c942b0}

when the rows with the first representation come back in a query and the array extension is enabled, I get the error...

Sequel::Error: invalid array, doesn't start with {

**Comment by jeremyevans** [comment]
The pg_array extension doesn't currently support arrays with explicit lower bounds.  This is the first time I've actually seen them used, I had to look up the PostgreSQL documentation to see that it was valid syntax.

It isn't difficult to add support to the pure ruby parser that ships with Sequel.  This also needs fixing in sequel_pg, which currently returns the wrong result instead of raising an exception.  I'll work on this and try to have a fix committed for it tomorrow.

**Comment by larskanis** [comment]
Rails 5 has switched from a pure ruby array parser to the builtin encoder and decoder of the pg.gem [here](https://github.com/larskanis/rails/commit/647eb2cf1cd65b0391e3584361f0fc76246e64f3) . However this expects a string starting with "{" as well.

I think it makes sense to add this feature directly in pg. How would you cast a value like this to ruby?
```
[3:5]={a,b,c}     # => [nil, nil, nil, "a", "b", "c"]
```
Since ruby array don't support lower bounds, this would cast back to the database like this:
```
{NULL,NULL,NULL,a,b,c}
```
But from the PostgreSQL view these are not equal:
```
[3:5]={a,b,c} != {NULL,NULL,NULL,a,b,c}
```
Any ideas, how to solve this?

**Comment by twillis** [comment]
can you refer me to the pg docs on lower bound arrays that you mentioned previously? I'm not familiar with these and yesterday was my first time running across them.

**Comment by jeremyevans** [comment]
My solution will just ignore the explicit bounds.  If the bounds aren't explicit, that means the lower bound starts at 1, while ruby arrays start at 0.  So there's always been a disconnect between PostgreSQL arrays and ruby arrays in regards to indexing.  This does mean that such values will not round trip, but I'm currently OK with that.  If someone really needs to produce PostgreSQL arrays with explicit bounds, that can be added later without too much difficulty.

**Comment by twillis** [comment]
I dont even know how I would persist them from app code that would result in explicit bounds happening. I think i'd like to avoid it all together so I like the proposed solution. I just dont know how those values got in our db in the first place. I am assuming our dba knows.

**Comment by larskanis** [comment]
@twillis It's described here: http://www.postgresql.org/docs/9.5/interactive/arrays.html#ARRAYS-IO

**Comment by larskanis** [comment]
@jeremyevans Makes sense. I'll add `PG::TextEncoder::Array#ignore_bounds` which will raise an error if set to `false` and will ignore the bounds if set to `true`.
