### ISSUE TITLE
Errors when copying binary data from sqlite to postgresql

### ISSUE THREAD

**Issue by kevincox** [jeremyevans/sequel#1135]
I don't know why is is an issue as the target column gets created as a `BYTEA` so I would think it should all work.

```
% sqlite3 test.db
SQLite version 3.10.1 2016-01-13 21:41:56
Enter ".help" for usage hints.
sqlite> CREATE TABLE test ( b BINARY );
sqlite> INSERT INTO test VALUES ( X'FF' );
sqlite> 
% sequel -C sqlite://test.db postgresql://...

Databases connections successful
Migrations dumped successfully
Tables created
Begin copying data
Begin copying records for table: test
Error: Sequel::DatabaseError: PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xff

/home/kevincox/.gem/ruby/2.3.0/gems/sequel-4.30.0/lib/sequel/adapters/postgres.rb:184:in `async_exec'
```

**Comment by jeremyevans** [comment]
This is expected.  Sequel only considers SQLite columns of type `blob` as blobs when retrieving records, not columns of type `binary`.  This is in line with SQLite's documentation (http://sqlite.org/datatype3.html, section 2.2).  The fact that a bytea column is used in PostgreSQL is due to the generic type handling in the schema dumper, as opposed to the SQLite-specific code used when retrieving values.

Your issue is similar to #1132, but for SQLite instead of Microsoft SQL Server. You need to convert the column values to `Sequel::SQL::Blob` values manually before inserting them into PostgreSQL.  This means you will not be able to use `sequel -C` to do this conversion, you'll have to write some custom code.
