### ISSUE TITLE
Defining a model before the migrations is not recommended

### ISSUE THREAD

**Issue by pjaspers** [jeremyevans/sequel#1138]
I realise this was probably not smart of me to start with, but in my tests I loaded the models before running the migrations, this had some weird behavior.

Example of what kept me busy for a couple of hours before I realised it was the load order:

``` ruby
require "sequel"

ENV["DATABASE_URL"] = "sqlite:/"

DB = Sequel.connect(ENV["DATABASE_URL"])

require 'sequel/plugins/serialization'
Sequel::Plugins::Serialization.register_format(:array,
                                               lambda{|v| v.join(",")},
                                               lambda{|v| v.split(",")})

class Operation < Sequel::Model
  plugin :serialization

  serialize_attributes :array, :project_ids
end

DB.create_table(:operations) do
  primary_key :id
  String :project_ids, text: true
  String :issue_ids, text: true
  String :worklog_ids, text: true
  String :log, text: true
  DateTime :created_at
  DateTime :updated_at
end

o = Operation.new
o.project_ids = [1,2,3]
o.save

on = Operation[o.id]
# Because the model was defined before the migrations, this would go boom:
#
#      sequel-4.30.0/lib/sequel/plugins/serialization.rb:162:in `block (3 levels) in define_serialized_attribute_accessor': super: no superclass method `project_ids' for #<Operation:0x007ff10c45b5a0> (NoMethodError)
#       Did you mean?  project_ids=
#
puts on.project_ids # => KAPUT
```
(updated code sample to inline the migration)

Like previously stated, this was probably not smart of me to begin with and I'm not sure if this is something that should be solved, just wanted to throw it out there.

**Comment by jeremyevans** [comment]
This isn't a bug in Sequel.    The README states: "When a model class is created, it parses the schema in the table from the database, and automatically sets up accessor methods for all of the columns in the table".  Since at the time you created the class, the columns didn't exist, no accessor methods were created. You should setup the schema before setting up your model classes.  I believe the migration documentation warns against using models in migrations, as well, as that is a bad practice.

**Comment by pjaspers** [comment]
Fair enough, didn't mean to imply it was q bug, just took me a while to figure out why ai could save it the first time but couldn't load it after finding.

Thanks for a great library, a real joy to use!
