### ISSUE TITLE
Support for BETWEEN

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1150]
I don't find anywhere (neither documentation or code) support for writing conditions using the SQL `BETWEEN` keyword

**Comment by jeremyevans** [comment]
You can do BETWEEN like queries using ranges:

```ruby
DB[:table].where(:column1=>1..10, :column2=>2...20)
```

For simplicity, this uses >= and <= or < instead of BETWEEN, as BETWEEN doesn't handle ranges with exclusive ends.

In the future, per the contribution guidelines, questions like this should be asked on IRC or sequel-talk.  GitHub Issues should only be used for reporting bugs.
