### ISSUE TITLE
Sequel hides fatal errors, does not check table existence

### ISSUE THREAD

**Issue by xzo** [jeremyevans/sequel#1160]
1) Sequel hides fatal errors - PG::UndefinedTable et al.
2) Sequel does not check table existence
3) 1-2 cause hidden bugs and crazy PG::InFailedSqlTransaction errors

```ruby
      def check_non_connection_error
        #...
        rescue
          nil
        end
      end

      def inherited(subclass)
        #...
            subclass.set_dataset(@dataset.clone, :inherited=>true) rescue nil
        #...
            subclass.set_dataset(subclass.implicit_table_name) rescue nil
        #...
      end

      def get_db_schema(reload = reload_db_schema?)
        #...
        get_columns = proc{check_non_connection_error{columns} || []}
        schema_array = check_non_connection_error{db.schema(dataset, :reload=>reload)} if db.supports_schema_parsing?
        #...
      end

      def set_dataset(ds, opts=OPTS)
        #...
          @columns = @dataset.columns rescue nil
        #...
        check_non_connection_error{@db_schema = (inherited ? superclass.db_schema : get_db_schema)}
        #...
      end

```

**Comment by jeremyevans** [comment]
Sequel supports creating model classes even if the underlying table doesn't exist or is not a table at all (such as a joined dataset or a table returning function).

The swallowing of errors is expected behavior, and required for certain things to work, such as the schema plugin or when `Model.set_dataset` is called after.  It may be better to use a more specific exception, but that wouldn't change things.

Unless you are creating model classes inside a transaction, it shouldn't matter.  If you are doing so on PostgreSQL, you can wrap each model class creation in a savepoint and that should fix things.

That's not to say there isn't room for improvement in this area, only that this behavior is currently expected and not a bug.

One possible option is the introduction of an optional strict mode that will not swallow errors.  I think that would be a good improvement, and possibly something we could turn on by default in Sequel 5.

Another possible approach would be to automatically use a savepoint around the `@dataset.columns` call in `set_dataset`, see an example: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/query.rb#L197

I'll try to implement both of these changes before the next release.
