### ISSUE TITLE
Mutating association cache

### ISSUE THREAD

**Issue by janko-m** [jeremyevans/sequel#1179]
### Complete Description of Issue

I was recently writing an example blog application using Sequel, and came to a surprising behaviour of association cache. When viewing a single post, on the same page I was listing comments for the post and had a form for adding a new comment. So in my request handling I had the following:

```rb
r.get "posts/:id" do |id|
  @post = Post.with_pk!(id)
  @comments = @post.comments
  @new_comment = Comment.new(post: @post)
  view "posts/show"
end
```

The surprising behaviour was that, even though that `@post` didn't have any saved comments, in the view `@comments` turned not to be empty, but contained the new unsaved comment. I'm aware what happened: `@post.comments` is a cached array of comments (which is empty), and then the next line appended the initialized comment, mutating the array. At first I expected that only the `@post` is assigned to the `@new_comment`, but I figured presumably because of reciprocal associations detection the comment was also added to the post.

My proposal is that, instead of mutating the association cache array, that the `+=` operator is used instead.

### Simplest Possible Self-Contained Example Showing the Bug

```rb
require "sequel"

DB = Sequel.sqlite

DB.create_table :posts do
  primary_key :id
end

DB.create_table :comments do
  primary_key :id
  foreign_key :post_id, :posts
end

class Post < Sequel::Model
  one_to_many :comments
end

class Comment < Sequel::Model
  many_to_one :post
end

post = Post.create
comments = post.comments
comment = Comment.new(post: post)
puts comments.count # outputs "1"
```

**Comment by jeremyevans** [comment]
This is expected behavior.  I don't think it makes sense to use  `+=` to create a new array, you could make the same argument for `@post.comments` that you are making for `@comments` even with that change.

If you don't want the new comment showing up with existing comments, you could just swap the lines:

```ruby
  @new_comment = Comment.new(post: @post)
  @comments = @post.comments
```

This is because the `Comment#post=` method only modifies the reciprocal association cache if it already exists.

Alternatively, since you aren't saving the comment, unless your view references `@new_comment.post`, you could just do `@new_comment = Comment.new`.

Another solution would be to set `:reciprocal=>nil` in the `Comment.many_to_one :post` association options.  Still another solution would be to call `@post.comments(:reload=>true)`.
