### ISSUE TITLE
Sequel model `set_dataset` doesn't respect `inheritance: true` option

### ISSUE THREAD

**Issue by okliv** [jeremyevans/sequel#1222]
### Complete Description of Issue

I have two models with class table inheritance between them

    class Topic < Sequel:Model
    
       plugin :class_table_inheritance, :key => :topic_type

    end

and 

    class Article < Topic

    end

next steps:

    $ bundle console

    > Article.dataset.sql

    #=> "SELECT `topics`.`entity`, `topics`.`name`, `topics`.`title`, `topics`.`subtitle`, `articles`.`author` FROM `topics` INNER JOIN `articles` ON (`articles`.`name` = `topics`.`name`)" 

    > Article.set_dataset :articles

    > Article.dataset.sql

    #=>  "SELECT * FROM `articles`"

    > Article.set_dataset :articles, inheritance: true

    > Article.dataset.sql
    
     #=> "SELECT * FROM `articles`"

so, `inheritance: true` doesn't return back normal CTI bevaviour to Article class

(i didn't find any documentation on this except inline code comments, so i can understand wrong this option, but looks like it misbehave)

or i can rephrase this issue/question: how can i re-initialize CTI model?

**Comment by jeremyevans** [comment]
Explicitly setting the dataset for models using CTI is not supported.  Either have `Article` be a subclass of `Topic`, in which case `Article.dataset` will be a joined dataset, or have `Article` subclass from `Sequel::Model`.

If you just want to share behavior between Topic and Article, consider using a module or a plugin.

**Comment by okliv** [comment]
Closely to my case, i have a lot of entities, described with uml class diagram (plantuml). i wrote a parser for that file (for any plantuml file) and now i want to `Object.const_set` all that entities. Like,

    def klass
      entity=self
      Class.new(sequel_superclass) do
        set_dataset entity.db_name.to_sym, inherited: entity.inherited
        plugin :class_table_inheritance, :key => entity.class_table_inheritance_column if entity.class_table_inheritance_column.presence
      end
    end

    def sequel_model_init
      Object.const_set name, klass unless Object.const_defined?(name)
      #name.constantize.set_datatset db_name, inherited: true
    end


but after `sequel_model_init` all i have for Article, for example (`Article.dataset.sql`) is #=> "SELECT * FROM `articles`" no matter i use `set_dataset` inside `Class.new {}` or as a singleton method

can you please suggest a (good) solution for dynamic model initialization? all i can imagine for now - is `class eval` all models definitions simulating explicit file-by-file declaration

**Comment by jeremyevans** [comment]
I don't think the issue here is dynamic model initialization.  The issue is you are trying to use class table inheritance with a custom dataset on a subclass, which isn't supported.  Your code should work fine as long as Article doesn't inherit from Topic, or if Topic doesn't use class table inheritance.  If you feel you must use class table inheritance with a custom dataset in the subclass, you should write your own plugin that will handle it  (though I have no idea how such a thing would even work).

It's also unsupported to use the :inherited flag to set_dataset, that's only for internal use (it's not documented).

**Comment by okliv** [comment]
define dataset explicitly - is not my need. i just have an error 

    Sequel::Error: No dataset associated with Class # Article in my example

 if i drop out `set_dataset` option.

so, i had to add it... (the default `Article < Topic` class initialization would be just great) 
maybe, i missed something there?

thanks

**Comment by jeremyevans** [comment]
Ah, I think I understand.  The class table inheritance plugin requires that subclasses have a name when being created, and using Class.new creates an anonymous class, which is why it probably doesn't work.

My guess is you'll need to do something like:

```ruby
  klass = eval("class #{name} < #{sequel_superclass}; self end")
```

as ruby does not offer another way to dynamically create a named class as far as I know (assigning `Class.new` return value to a constant doesn't name the class until something requests the class's name).

**Comment by okliv** [comment]
awh.. as i thought... i had an illusion that `set_dataset` with "inheritance: true" option can "glue" things together (superclass and class) during dynamic subclass definition, because looked like it has all it needs for this... thanks..
