### ISSUE TITLE
Bignum is deprecated/removed in Ruby 2.4

### ISSUE THREAD

**Issue by ioquatix** [jeremyevans/sequel#1245]
Just wondering if this will affect sequel. Thanks.

**Comment by janko-m** [comment]
@ioquatix Jeremy already addressed this back in version [4.35.0](http://sequel.jeremyevans.net/rdoc/files/doc/release_notes/4_35_0_txt.html).

**Comment by ioquatix** [comment]
Interesting. Adding a symbol doesn't seem like a great way to solve this problem, but I guess it works. What about having Integer but specifying bit/byte size/length. e.g. Integer :foo, size: 4 or size:8

**Comment by jeremyevans** [comment]
I don't think a :size option would make sense, since sizes other than 4/8 are not supported by most databases.  I agree that using the :Bignum symbol is less than ideal, but it's the simplest solution I could think of considering that ruby itself is dropping backwards compatibility.  Note that `Bignum :foo` works, since that calls the Bignum method instead of referencing the Bignum class. Closing now as this in't a bug report.

**Comment by jeremyevans** [comment]
As the contribution guidelines state, have discussions on the Google Group or IRC, GitHub Issues is only used for bug reports.  It's not really fair to complain when you post things that violate the contribution guidelines.

Whether or not it is a good idea to use ruby class names for database-independent types, that's that route Sequel took, and changing it doesn't make much sense at this point.  Do you have a specific recommendation in this area that is backwards compatible?

Just so you know, MySQL is not "most databases". Even if most databases supported 1/2/4/8, what are you supposed to do with `size: 7`?  If you want to use database specific types, Sequel makes that very easy to do, by just providing the database specific type name instead of using a ruby class.

**Comment by ioquatix** [comment]
Sorry @jeremyevans I wasn't really complaining, but really just stating my feeling on the issue. Also, I'll move to the Google groups. It was not my intention to waste time :)
