### ISSUE TITLE
self define sql function run in slave DB

### ISSUE THREAD

**Issue by kg1990** [jeremyevans/sequel#1256]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

I define a function in database(postgresql)
named  create_order(somthing params)
when i use
```
result = DB["select create_order(1,2,3)"]
```
I got this error
```
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.38.0/lib/sequel/adapters/postgres.rb:187:in `async_exec': PG::ReadOnlySqlTransaction: ERROR:  cannot execute SELECT FOR UPDATE in a read-only transaction (Sequel::DatabaseError)
```

How sequel mark a select query and run in read_only equirment?
can support database function?

waiting for u answer, best wishes!

**Comment by jeremyevans** [comment]
This isn't a bug in Sequel, this is an issue in the database, and without seeing the definition of create_order, I assume the problem is in the that function.  The ruby code you are displaying can't possibly generate the error you are displaying, as it just creates a dataset, it doesn't execute it in the database, the error you are showing must be raised later when the query is executed.

As the contribution guidelines state, and as displayed at the top of your bug report, please use the sequel-talk Google Group or IRC for similar questions in the future, as GitHub issues should only be used for reporting bugs in the library.
