### ISSUE TITLE
Migration column type unexpected behavior

### ISSUE THREAD

**Issue by dikond** [jeremyevans/sequel#1268]
Hello! I've encountered surprising behaviour while doing migrations. 

### Complete Description of Issue
I've specified column type of `String` class. Migration succeeded, but when I've checked the table through `psql` it showed the column type of `text`. I only had a `null: false` option there. If I will specify `text: false` it will create a column with `character varying(255)` type, which is expected by default, with omitted option.

I've also tried to pass the type as `:string` or `"string". But in this case I am getting PG error:

```
E, [2016-11-25T18:06:29.186995 #40661] ERROR -- : PG::UndefinedObject: ERROR:  type "string" does not exist
LINE 1: ... NOT NULL, "name2" varchar(255) NOT NULL, "name3" string, "n...
```

My `psql --version` gives `psql (PostgreSQL) 9.6.1`

### Simplest Possible Self-Contained Example Showing the Bug
```
Sequel.migration do
  up do
    create_table :areas do
      primary_key :id
      column :name0, String
      column :name2, String, null: false, text: false
      column :name3, :string
      column :name4, 'string'
    end
  end
  down do
    drop_table :areas
  end
end
```

I am ready to provide further information.

**Comment by jeremyevans** [comment]
This is expected behavior.  Have you read the schema modification guide http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html)? Specifically, it says "So while you specified `String`, Sequel will actually use `varchar` or `text` depending on the underlying database."  On PostgreSQL, Sequel uses `text` for `String`, since that doesn't have a very small character limit.  If you really want `varchar(255)`, specify `:size=>255` as an option.

**Comment by dikond** [comment]
Sorry, I've read it but no closely enough. I was looking at the code below that explanation and my first guess was that Sequel will try to use `varchar` by default. Perhaps my expectations was also driven by the ActiveRecord background.
