### ISSUE TITLE
`exclude` also excludes columns with NULL values.

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [jeremyevans/sequel#1276]
### Complete Description of Issue

Using `exclude` with a nullable column excludes not only the rows with the given value, but also any rows with that column set to `NULL`.

The documentation for `exclude` says that it performs the inverse of `where`, but this behavior is not consistent with that explanation.

I think inverting direct equality with a nullable column should generate `("column" != value OR "column" IS NULL)`. Nesting it within parentheses maintains the expected grouping of clauses.

### Simplest Possible Self-Contained Example Showing the Bug

```
DB.create_table :test do
  primary_key :id
  Integer :num
end

DB[:test].insert({ num: 1 })
DB[:test].insert({ num: 2 })
DB[:test].insert({})

assert_equal 3, DB[:test].count
assert_equal 1, DB[:test].where(num: 1).count
# fails
assert_equal 2, DB[:test].exclude(num: 1).count
```

Note also that a "quick fix" also fails because the same key is used twice:
```
DB[:test].insert({ num: 1 }) # Add this so assertion actually fails
# also fails (returns 3)
assert_equal 2, DB[:test].exclude(num: 1, num: nil).count
```

Similar approaches that would initially seem viable also fail in the same way:
```
# returns 3
assert_equal 2, DB[:test].exclude([num: 1], [num: nil]).count
```

The cleanest way I can find to get the desired behavior is:
```
assert_equal 2, DB[:test].where(Sequel.|(Sequel.~(num: 1), num: nil))
```
but this clearly not as simple as swapping `where` with `excludes`.

**Comment by jeremyevans** [comment]
This is expected behavior.  `exclude` does the inverse of `where`, but in SQL, the inverse of `expr = NULL` is `expr != NULL`, which in both cases evaluates to `NULL`. Don't forget, SQL uses 3-valued boolean logic, not 2-valued boolean logic.  If you really want to allow to handle `NULL` values, you need to consider the `NULL` case separately:

```ruby
DB[:t].where(Sequel.~(:a=>nil) & {:a=>1})
# SELECT * FROM t WHERE ((a IS NOT NULL) AND (a = 1))
DB[:t].exclude(Sequel.~(:a=>nil) & {:a=>1})
# SELECT * FROM t WHERE ((a IS NULL) OR (a != 1))
```

I can see how this may be confusing to someone not familiar with SQL's 3-valued boolean logic, so I'll try to improve the documentation for `exclude` and `invert` to mention this.
