### ISSUE TITLE
Migrations do not work with mysql and utf8mb4

### ISSUE THREAD

**Issue by mfinelli** [jeremyevans/sequel#1282]
### Complete Description of Issue

The default `schema_migrations` table sets a primary key on the `filename` column which defaults to a varchar(255). However, this results in an index too big for mysql when the default character set (set in `/etc/mysql/my.cnf` for example) is set to `utf8mb4`.

The solution is to limit the column length of this column to `190` or to force to some other character set (such as plain utf8). The former is probably preferred so that multibyte filenames can be properly supported.

### Simplest Possible Self-Contained Example Showing the Bug

Just try to run migrations with mysql and the default character set as above (utf8mb4). It will fail to create the migrations table.

`Sequel::DatabaseError: Mysql2::Error: Specified key was too long; max key length is 767 bytes`

**Comment by jeremyevans** [comment]
In terms of making this change, it's not backwards compatible, so we'd only want to do it if we are using MySQL and the default charset is utf8mb4.  We could probably try to determine that up front, or just rescue an exception, check for that error message, and retry with a size of 190.  Retrying on error may be better in the long run, in case MySQL fixes their issue (this is a limitation in MySQL, not a bug in Sequel).  I'll try to work on that tomorrow.

One simple way to work around this is to create the schema_migrations table manually before running migrations.  Another is to use integer migrations instead of timestamp migrations.
