### ISSUE TITLE
MySQL: Sequel::SQL::Blob column always in changed_columns

### ISSUE THREAD

**Issue by oldgreen** [jeremyevans/sequel#1287]
Assigning the same String (or Sequel::SQL::Blob) value to a Sequel::SQL::Blob column of a Sequel::Model instance marks the column as changed.

```
  irb(main):010:0> DB.adapter_scheme
  => :mysql2
  irb(main):011:0> DB.create_table(:items) {primary_key :id; File :a}
    DEBUG -  (0.007878s) CREATE TABLE `items` (`id` integer PRIMARY KEY AUTO_INCREMENT, `a` blob)
  => nil
  irb(main):012:0> A = 'a'.freeze
  => "a"
  irb(main):013:0> A.class
  => String
  irb(main):014:0> item = Item.create(:a => A)
    DEBUG -  (0.000181s) BEGIN
    DEBUG -  (0.000229s) INSERT INTO `items` (`a`) VALUES (0x61)
    DEBUG -  (0.000270s) SELECT * FROM `items` WHERE (`id` = 1) LIMIT 1
    DEBUG -  (0.000105s) COMMIT
  => #<Item @values={:id=>1, :a=>"a"}>
  irb(main):015:0> item.changed_columns
  => []
  irb(main):016:0> item.a = A
  => "a"
  irb(main):017:0> item.changed_columns
  => [:a]
```

Using `Sequel::SQL::Blob` instead of a `String` makes no difference, because in `Sequel::Model#[]=` (https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/base.rb#L1340) the class of `v` (result of `typecast_value()`) is always `Sequel::SQL::Blob` and the class of `c` (the value from `@values` hash) is always `String` so the result of the condition is always `true`.

```
  irb(main):018:0> B = Sequel::SQL::Blob.new('a').freeze
  => "a"
  irb(main):019:0> B.class
  => Sequel::SQL::Blob
  irb(main):020:0> item = Item.create(:a => B)
    DEBUG -  (0.000192s) BEGIN
    DEBUG -  (0.000272s) INSERT INTO `items` (`a`) VALUES (0x61)
    DEBUG -  (0.000335s) SELECT * FROM `items` WHERE (`id` = 2) LIMIT 1
    DEBUG -  (0.000143s) COMMIT
  => #<Item @values={:id=>2, :a=>"a"}>
  irb(main):021:0> item.changed_columns
  => []
  irb(main):022:0> item.a = B
  => "a"
  irb(main):023:0> item.changed_columns
  => [:a]
```

**Comment by jeremyevans** [comment]
This is expected, since the class is being changed.  You can use the typecast_on_load plugin to fix the typecasting when the model instance is created, so the column will start out with the correct type: `Item.plugin :typecast_on_load, :a`.

The underlying reason for this issue is that mysql2 does not expose support for modifying the typecasting of blob columns, so Sequel cannot automatically typecast.  You could switch to the mysql adapter, as that will work without the typecast_on_load plugin.  You may want to contact the mysql2 developers and ask them to add support for customizable typecasting of blobs if you want to fix the underlying issue.
