### ISSUE TITLE
Add custom `#inspect` for Sequel::SQL::Blob

### ISSUE THREAD

**Issue by backus** [jeremyevans/sequel#1293]
It can be very confusing to test code that involves blobs because it is very unclear whether you have a bug or one of your values is secretly a `Sequel::SQL::Blob` type. This ended up being a problem for me so many times that I ended up adding this to my spec helper

```ruby
class Sequel::SQL::Blob
  def inspect
    "#<#{Sequel::SQL::Blob} #{super}>"
  end
end
```

and I view this as a usability bug which is why I'm reporting here and not on the mailing list. I'll give an example below

#### Sample DB

```sh
createdb exampledb
```

```sql
CREATE TABLE things (
    id integer,
    data bytea
);
```

#### Example confusing test

```ruby
# frozen_string_literal: true
require 'sequel'
DB = Sequel.connect('postgres://localhost/exampledb')

require 'rspec'

RSpec.describe 'confusing failure' do
  it 'should match what was inserted' do
    data = "\x7a\x85\x99\xa6\x38\x7d\x1b\x69"
    DB[:things].insert(id: 1, data: Sequel.blob(data))

    expect(DB[:things].first).to eq(
      id:   1,
      data: data
    )
  end
end
```

#### Output

```sh
$ rspec example.rb
F

Failures:

  1) confusing failure should match what was inserted
     Failure/Error:
       expect(DB[:things].first).to eq(
         id:   1,
         data: data
       )

       expected: {:id=>1, :data=>"z\x85\x99\xA68}\ei"}
            got: {:id=>1, :data=>"z\x85\x99\xA68}\ei"}

       (compared using ==)
     # ./example.rb:13:in `block (2 levels) in <top (required)>'

Finished in 0.0526 seconds (files took 0.64033 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./example.rb:9 # confusing failure should match what was inserted
```

Now in this case the inserted record is pretty simple so it would only take a few seconds to be able to tell that the data is exactly the same. In my case though (and I think this is similar to the average use case) the blob data is much bigger and it is almost impossible to be able to tell by eyeballing the output whether the bytea fields involved in the failure output are actually the same values.

Applying the patch to the specs I mentioned above makes this a non issue:

```sh
$ rspec example.rb
F

Failures:

  1) confusing failure should match what was inserted
     Failure/Error:
       expect(DB[:things].first).to eq(
         id:   1,
         data: data
       )

       expected: {:id=>1, :data=>"z\x85\x99\xA68}\ei"}
            got: {:id=>1, :data=>#<Sequel::SQL::Blob "z\x85\x99\xA68}\ei">}

       (compared using ==)

       Diff:
       @@ -1,3 +1,3 @@
       -:data => "z\x85\x99\xA68}\ei",
       +:data => #<Sequel::SQL::Blob "z\x85\x99\xA68}\ei">,
        :id => 1,
     # ./example.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.0504 seconds (files took 0.57833 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./example.rb:15 # confusing failure should match what was inserted

**Comment by backus** [comment]
I'd be happy to PR this if you agree by the way

**Comment by jeremyevans** [comment]
This isn't something we do in other places where we subclass a core class (e.g. Sequel::SQLTime, Sequel::Model::Associations::AssociationReflection), but I suppose I could consider changing things.  If we do it for Sequel::SQL::Blob, we should probably make similar changes for the other classes at the same time.

For Sequel::SQL::Blob, I'm not sure just using the class name and whole string makes sense, because as you mention, blobs can be quite large.  Maybe something like: 

```
#<Sequel::SQL::Blob:0x1234567890abcd bytes:1234567 start:"first 10 bytes" end:"last 10 bytes">
```

I'm not a heavy user of blobs myself, and before making this change I'd like to get feedback from the community before making a decision. As changing inspect is a feature request and not a bug, such discussion should happen on the Google Group.  Can you please add a post on the Google Group?

FWIW, I'm not sure why your spec would be failing if the string has the same content as the blob:

```ruby
'a' ==  Sequel::SQL::Blob.new('a')
# => true
```

Maybe an encoding issue?

**Comment by backus** [comment]
Sure I'll add a post to the google group later today.

> Maybe an encoding issue?

Yup. In my use case (and in the example above) the postgres type is `bytea` so the string within the blob is encoded as `ascii-8bit`.
