### ISSUE TITLE
Add method to get enum values directly

### ISSUE THREAD

**Issue by aidalgol** [jeremyevans/sequel#1303]
I would like a method for getting the values of an enum in a PostgreSQL database.  Presently, the only way to retrieve this data is by examining the schema of a table with a column of the enum type.

For example:
```ruby
DB.schema(:table_name)
[[:column_name, {:type=>:enum, :enum_values=>['value1', 'value2']}]]
```

I would like an interface more like this:
```ruby
DB.enum_values(:enum)
=> ['value1', value2']
```

**Comment by jeremyevans** [comment]
I'm not opposed to this, but I'm not sure how useful it is.  If you have a type but no column of that type, does it really matter what values are valid for the type?  This would require keeping a separate hash for enums keyed by type name instead of oid.

As explained in the contribution guidelines, GitHub issues should only be used to report bugs in Sequel.  Feature requests like this should be posted on the sequel-talk Google Group.  So if you would like to see this added to Sequel, please post on the Google Group and see if there is any community support for the idea.

**Comment by aidalgol** [comment]
Oops!  I'm very sorry about this.  I misread that part of the contribution guidelines.
