### ISSUE TITLE
Mysql2 Adapter does not honor named timezones for application_timezone

### ISSUE THREAD

**Issue by Aryk** [jeremyevans/sequel#1310]
When using the mysql2 adapter, the application_timezone is not honored unless you put :utc or :local as the application_timezone.

However, this can be misleading because if you want to use the named_timezones extension and specify something like:

```ruby
#   Sequel.database_timezone = 'America/New_York'
#   Sequel.application_timezone = 'America/Los_Angeles'
``` 

It will not honor the application_timezone at all.

My take is that this was a design limitation of the mysql2 adapter and would have to be handled in the Sequel gem itself. I think ActiveRecord does the conversion in it's library.

Here is another user who ran into the same [issue](http://stackoverflow.com/questions/30334892/mysql2-gem-casting-datetime-objects-from-remote-db-in-local-server-time).

@jeremyevans - What is your suggestion for combating this limitation?

**Comment by jeremyevans** [comment]
If you need to use the named_timezones extension, use the mysql adapter instead of mysql2 adapter.  The named_timezones extension documents that it only works on certain adapters, and the mysql2 adapter is not listed.  If you want the mysql2 adapter to support named_timezones, you'll have to get the mysql2 driver maintainers to add support for custom type conversions.

**Comment by Aryk** [comment]
Got it, I researched the issue a little more, for those interested: http://stackoverflow.com/questions/5411551/what-the-difference-between-mysql-and-mysql2-gem

If I want to keep the mysql2 gem, I'd have to do the conversions at the Sequel model layer it seems. Have you seen anyone do this with a plugin, maybe I can contribute to that effort.
