### ISSUE TITLE
MySQL driver acquires a pool connection for each placeholder that needs escaping 

### ISSUE THREAD

**Issue by KJTsanaktsidis** [jeremyevans/sequel#1319]
### Complete Description of Issue

As discussed in #784, the only way to correctly escape strings in MySQL is to do it with an open connection, since it depends on the connection's encoding and the value of `sql_mode`. Because of this, `Sequel::MySQL2#literal_string_append` uses `db.synchronize` to check a connection out of the pool.

Unfortunately, when executing a query with a large number of `?` placeholders in it using `Sequel::Dataset#fetch`, `literal_string_append` gets called once per placeholder to escape the text that must go in there. If the connection pool is under contention, this causes massive slowdown of requests; for every placeholder in a query, the thread gets sent to the back of the queue for the connection pool. We had an instance where some requests were spending ~20 seconds waiting for connections, even though the pool timeout was set to 5 seconds, for this reason.

This is not a problem if `db.synchronize`has been called at a higher level (perhaps via `db.transaction`) in the stack already, because the connection has already been checked out and it is simply a fast threadlocal access to get the connection during placeholder escaping.

I should also note that it is not strictly speaking correct to do the call to `mysql_real_escape_string` on a different connection to the one the query is going to be executed on, since the locale and sql_mode can be set on a per-connection basis.

We have therefore solved this in our use case with the following monkey patch, which wraps all of the Sequel dataset action methods in `db.synchronize`.

```ruby
module Sequel
    class Dataset
        ACTION_METHODS.each do |action|
            # Sequel does not actually have all of these methods?
            next unless self.method_defined? action
            eval_text = <<~'RUBY'
                alias_method "__old_unwrapped_%{escaped_action_name}".to_sym, "%{action}".to_sym
                def %{action}(*args)
                    if block_given?
                        db.synchronize {
                            return self.__old_unwrapped_%{escaped_action_name}(*args) { |*block_args| yield *block_args }
                        }
                    else
                        db.synchronize {
                            return self.__old_unwrapped_%{escaped_action_name}(*args)
                        }
                    end
                end
            RUBY
            eval_text = eval_text % {
                action: action,
                # Unfortunately, "__old_unwrapped_<<" is not a valid ruby method name.
                escaped_action_name: action.to_s
                                        .gsub('<', 'lt')
                                        .gsub('>', 'gt')
                                        .gsub('[', 'lbrace')
                                        .gsub(']', 'rbrace')
            }
            class_eval eval_text
        end
    end
end
```

I think there's a compelling argument that this should in fact be the default behaviour for at least MySQL databases in Sequel. I haven't looked at other adapters, but if their escaping also depends on connection state then the same issues apply. If the maintainers agree, I can turn this into a useful PR with less violence.

**Comment by jeremyevans** [comment]
This is only necessary to escape strings, and many queries do not escape strings at all, so checking out a connection for every query seems unnecessary.  There are corner cases like the ones you are hitting, but those are simple to work around in your code by using `synchronize` manually.

I do not think what you propose should be the default behavior, but I'm OK with shipping a dataset extension with Sequel that does something similar.  You would want to use `super` instead of aliasing methods.  You should probably only use `synchronize` for the following sql methods: `select_sql`, `delete_sql`, `insert_sql`, `update_sql`, not for all action methods.  Additionally, you need to respect any server/shard information set on the dataset: `db.synchronize(@opts[:server])`.  Please submit a PR if you would like to see such an extension ship with Sequel.

**Comment by KJTsanaktsidis** [comment]
Thanks for the prompt response and the pointers for how to implement this correctly inside Sequel.

I deliberately did this above the level of `*_sql`; whilst checking out a connection at that level would stop the checkout-per-placeholder bug, the escaping would still not be done on the same connection as a query. This could actually be a security problem; a connection that was put into the wrong state by some bug (such as the application inappropriately setting `sql_mode` or encoding) could cause the wrong escaping to be done on interpolated strings and hence SQL injection.

Every query is going to eventually need a connection to do the actual query; is your concern about wrapping every Dataset method that the connection would be checked out for too long? Or is there some other behaviour I'm not aware of?

**Comment by jeremyevans** [comment]
If you have an application doing anything that modifies per-connection state and returns the connection to the pool without resetting the state, you have a potential issue.  Trying to prevent issues that modifying per-connection state causes just in this particular case doesn't make much sense since this is a general issue.

If you just do this for all action methods, you end up not doing it for people who call the `*_sql` methods directly.  Also, some action methods may perform substantial processing after the connection is used, in which case you have a connection checked out from the pool that could be used for other connections (e.g. `dataset.all{ expensive code here }`).

Note that you can certainly ship your own external extension that handles this case, and handle it any way you want.  I'm happy linking to such an extension from Sequel's website.  But if this is included in Sequel, it should be at the `*_sql` method level.

Note that in general if you have high levels of contention in the connection pool, you may be better served by increasing the number of connections then trying to work around the contention in this manner.

**Comment by KJTsanaktsidis** [comment]
Right - that makes good sense. I hadn't considered that `.each` and `all` execute a user-provided block. I'll try and find some time to write a dataset extension and submit a PR.

**Comment by KJTsanaktsidis** [comment]
I've gone and written the dataset extension you suggested and PR'd it in #1451
