### ISSUE TITLE
sequel dumps existing [big]serial column as standard bigint and without marked as autoincrement

### ISSUE THREAD

**Issue by gencer** [jeremyevans/sequel#1324]
When execute the following command;

`sequel -D postgres://postgres@127.0.0.1/statuses > schema.rb`

I get every table's primary key as `BIGINT`. Instead, it should be BIGSERIAL or if not at least should add `:bigserial` but it exports as standard `bigint` value and when loading this schema to empty database, all tables are became broken.

Is that a normal behavior and if so, why? How can we overcome on this?

**This:**
`primary_key :id, :type=>"bigint"`

**should be:**
`primary_key :id, :bigserial, :type=>"bigint"`
right?

**Notes**:
1. I use PostgreSQL 9.6.2 on Linux also Ruby 2.4.0  and Sequel 4.44 used.
2. I couldn't find anything regarding to SERIAL or BIGSERIAL subjects on doc/ folder.

**Update**:
As stated here autoincrement is set by default when needed: https://github.com/jeremyevans/sequel/issues/919. **But still**, it is load as bigint not as serial on postgres db.

**Comment by jeremyevans** [comment]
Thanks for the report, I agree that this is a bug.

This appears to be handled correctly if you use the database independent dump (`sequel -d`), giving you

```ruby
  primary_key :id, :type=>:Bignum
  # "id" bigserial PRIMARY KEY
```

It's not handled correctly by the database dependent dump, because that uses "bigint" (the actual column type), and `primary_key :id, :type=>'bigint'` is interpreted by Sequel to mean you specifically want "bigint".

I think the fix would be to specify `:type=>:Bignum` for bigint primary key columns that have a sequence default, even in the database specific dump case.

**Comment by gencer** [comment]
Great to hear that. I was thinking that I do something wrong on this.

I am very new (to Ruby) on this so I would kindly like to await your fix/commit on this (even as soon as possible I can even use `master` branch)

Now If I use your way:
```
create_table(:categories) do
      primary_key :id, :type=>:Bignum
      column :user_id, "bigint", :default=>0, :null=>false
      column :subject, "character varying(255)", :null=>false
end
```
And run my custom command (I use multiple Sequel DB instances):

`rails mail:db:schema:load`

Result:
```
CREATE TABLE "public"."NewTable" (
"id" int8 DEFAULT nextval('categories_id_seq'::regclass) NOT NULL,
...
```

Done!.
