### ISSUE TITLE
jsonb column cannot get default value

### ISSUE THREAD

**Issue by devvit** [jeremyevans/sequel#1330]
### pg table like this, photos columns with default value

![pg table](http://i.imgur.com/Gj8Asfr.png)

### code

```ruby
DB = Sequel.connect(adapter: 'postgres', database: 'town_dev')
DB.extension :pg_json

Sequel::Model.plugin :defaults_setter

class Post < Sequel::Model

end
```

### output

![output](http://i.imgur.com/Wr2MPsX.png)

### column score(int type) work well, except photos column

**Comment by jeremyevans** [comment]
Parsing arbitrary default values is not something that Sequel can do, because it requires a full SQL parser specific to the database, and Sequel does not parse SQL.  It's possible that this particular case could be handled, but it invites the slippery slope, since everyone will want custom parsers for their specific case.  That's not a path I want to go down.

The default_values plugin already has support for setting the default value manually for specific columns, you should use that:

```ruby
Post.default_values[:photos] = lambda{Sequel.pg_jsonb('hello'=>'world')}
```
