### ISSUE TITLE
#update_only updates "*only" fields AND modified fields

### ISSUE THREAD

**Issue by a0s** [jeremyevans/sequel#1341]
Hi! I found that #update_only updates "*only" fields AND fields that was modified (because call save_changes). Is it true behaviour? Because something with the name "update_only" updates not only as a result.

**Comment by jeremyevans** [comment]
`update_only` is basically `set_only` followed by `update`, and by design it updates all modified columns after the update, so this isn't a bug.  If you only want to modify certain columns, use `set_only` followed by `save(:columns=>[:column1, :column2])`, but be aware that will update `:column1` and `:column2` even if the values haven't changed.

FWIW, `update_only` is deprecated, it is recommended to use `update_fields` instead (though that also will save all modified columns, not just the columns you pass to `update_fields`).
