### ISSUE TITLE
migrate sqlite3  to postgresql  VERROR  C22001  Mvalue too long for type character varying(32)

### ISSUE THREAD

**Issue by xyhc** [jeremyevans/sequel#1350]
I used sequel to migrate sqlite3  to postgresql

sqlite3   version
3.6.20
postgresql  version
9.6.2

when i run this command
sequel -C sqlite://data.db postgres://postgres:postgres@localhost/good

then ERROR happen
Error: DatabaseError: ERROR     VERROR  C22001  Mvalue too long for type character varying(32)  Fvarchar.c      L624 Rvarchar
/usr/lib/ruby/gems/1.8/gems/postgres-pr-0.7.0/lib/postgres-pr/connection.rb:145:in `query'

How can I solve this problem???

**Comment by jeremyevans** [comment]
If I had to guess, you have a `varchar(32)` type in your SQLite database, but you have more than 32 characters in it (SQLite doesn't check lengths).  Fix your SQLite database so that no column values has more than the number of characters specified by the column type, then try again.  Alternatively, dump the SQLite database schema using `sequel -d sqlite://data.db`, modify the migration it creates to make the column sizes larger, load the migration into the PostgreSQL database, then migrate the data manually.

**Comment by xyhc** [comment]
thanks !    
i  try it

**Comment by xyhc** [comment]
I  alter table varchar(32) to varchar(255) , the issue is fixed.  but there is another problem happen: 
Begin adding foreign key constraints
Error: DatabaseError: ERROR     VERROR  C42P01  Mrelation "clusters" does not exist     Fnamespace.c   L420    RRangeVarGetRelidExtended
/usr/lib/ruby/gems/1.8/gems/postgres-pr-0.7.0/lib/postgres-pr/connection.rb:145:in `query'

**Comment by jeremyevans** [comment]
From that error message, it looks like your SQLite database has a foreign key constraint to a table that does not exist.  Funnily enough, SQLite allows that as well, though if you enable foreign key support, trying to insert into the table will raise an error.  Either remove the foreign key constraint or change it to reference the correct table.

**Comment by xyhc** [comment]
OK ,  thanks a lot !
