### ISSUE TITLE
server_block: make set_default_server and clear_default_server available

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1352]
Sinatra doesn't have around filters, so would be quite useful to use `server_block` plugin with just before and after filters, through methods `set_default_server` and `clear_default_server`

**Comment by jeremyevans** [comment]
By design, just like connection checkouts and transactions, Sequel only offers a block based API for setting default servers, because that is the only way to make sure things are unset correctly.  Use a rack middleware in your Sinatra app and call `with_server` inside it, that will offer an around filter-like capability.

**Comment by brauliobo** [comment]
A rack middleware isn't convenient as there are preloaded data to be checked before picking a server.

**Comment by jeremyevans** [comment]
You can always ask Sinatra to support around filters.  Or use something like Roda which natively supports a block based API.

In any case, the methods you are asking for are unsafe and will not be added to Sequel.  Now, this is ruby, you can certainly define such methods yourself.

**Comment by brauliobo** [comment]
yep, I'm currently calling them using `send`, seems to work fine :)

**Comment by brauliobo** [comment]
Had to clear without `clear_default_server` to safely remove all picked servers
```ruby
servers = DB.pool.instance_variable_get :@default_servers
servers.delete Thread.current
```
