### ISSUE TITLE
String in schema modification documentation

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/sequel#1353]
### Complete Description of Issue

Documentation of [schema_modification](http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html):

```ruby
String :a1                          # varchar(255)
String :a5, :text=>true             # text
```

Reality: without `text` option default type is `text`.

I think the documentation needs to be fixed.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
set_column_type :table, :field, String
set_column_type :table, :field, String, text: false
```

### SQL Log (if any)

```sql
ALTER TABLE "table" ALTER COLUMN "field" TYPE text
ALTER TABLE "table" ALTER COLUMN "field" TYPE varchar(255)
```

### Environment

Sequel: `4.45.0`
Ruby: `2.4.1`
PostgreSQL: `9.6.2`

**Comment by jeremyevans** [comment]
The code example shows Sequel's defaults.  The PostgreSQL support overrides the defaults.  I think it is unreasonable to document all cases where database adapters override the defaults in the schema modification guide.

The documentation already states this directly above the code example you site: "Most method calls inside the create_table block will create columns, since method_missing calls column. Columns are generally created by specifying the column type as the method name, followed by the column name symbol to use, and after that any options that should be used. If the method is a ruby class name that Sequel recognizes, Sequel will transform it into the appropriate type for the given database. So while you specified String, Sequel will actually use varchar or text depending on the underlying database."

I think that is sufficient, but if you disagree, please send a pull request.

**Comment by AlexWayfer** [comment]
Sorry, did not notice this text.

Is it worth it to list the defaults for adapters? In the form of a table or the like. But I'm not sure.

**Comment by jeremyevans** [comment]
I don't think it makes sense to list the defaults for each database type.  Sequel supports around 11 database types just in the adapters that ship with it, and external adapters would have their own behavior.

If the user cares about a specific database type, they should specify it as a symbol or string. Use of ruby classes as types is for when you want database-agnostic behavior and don't care which specific database type is used.

**Comment by AlexWayfer** [comment]
Okay, thank you.
