### ISSUE TITLE
Using class_table_inheritance with alias sets wrong table_name

### ISSUE THREAD

**Issue by phyrog** [jeremyevans/sequel#1364]
### Complete Description of Issue

When using the `alias` option with the class table inheritance plugin, calling `Subclass.table_name` returns the table name of the superclass instead of the table name of the subclass. This has come up when using the `have_column` rspec matcher in a test (it checks the wrong table for the column).

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
class Foo1 < Sequel::Model
  plugin :class_table_inheritance, key: :kind
end

class Bar1 < Foo1
end

class Foo2 < Sequel::Model
  plugin :class_table_inheritance, key: :kind, alias: :foo2s
end

class Bar2 < Foo2
end

puts(Foo1.table_name) # => foo1s
puts(Bar1.table_name) # => bar1s
puts(Foo2.table_name) # => foo2s
puts(Bar2.table_name) # => foo2s
```

I realize that this is because we inherit `Foo2`, so the `alias` will be the same. Is this the intended behavior? Using `set_dataset :bar2s` in the subclass does not work, as it will query the `bar2s` table for columns defined in `foo2s`. It feels like the `alias` should be ignored when setting the `table_name`, as using an alias that does not exist as a table will result in a `table_name` that does not reference a table.

**Comment by jeremyevans** [comment]
It is expected when using the `:alias` option that the table name will be the same, because the subquery alias remains the same.  Sequel doesn't ship with a `have_column` rspec matcher, but you should probably contact the maintainer of that code and let them know they need to update the code if they want it to work with the class_table_inheritance :alias option.
