### ISSUE TITLE
Using lower function in query get unexpected result

### ISSUE THREAD

**Issue by vhtien** [jeremyevans/sequel#1366]
Hi guys,

I'm using Sequel to execute SQL but get an unexpected result when using lower/upper function inside the query.

```ruby
db = Sequel.connect jdbc_url, username: username, password: password
puts db.fetch('Select login, lower(role) from users').map { |h| h }
```
will print `{:login=>"abc@hello.sequel", :lower=>"admin"}`

while changing the query into `Select login, role from users` will get the result `{:login=>"abc@hello.sequel", :role=>"admin"}`

A workaround for it is using alias: `Select login, lower(role) as role from users`

Thank you!

**Comment by jeremyevans** [comment]
This is expected behavior.  If you use an expression, Sequel uses the name the database driver gives for the column.  On same databases, that will be `lower`, on some `lower(role)`, on others it will be nil and Sequel will use `untitled`.  The best practice is to always alias expressions when selecting them in Sequel.
