### ISSUE TITLE
find_or_create race conditions

### ISSUE THREAD

**Issue by rosenfeld** [jeremyevans/sequel#1372]
Hi Jeremy. Today I noticed once more a bug that rarely happens in our application, but this time I wanted to better understand it. 

The problem is related to find_or_create returning nil, which I suspect is a Sequel bug.

Here's the deal, we use PostgreSQL and it seems Sequel is smart enough to only create the record if it doesn't exist, which is good. I'm talking about the Sequel built-in protection for race conditions. Sequel will generate an insert statement like "insert into ... 1234, select ... where id not in (...) returning id", or something like that.

The problem is that when the record exists because it was created by another request in between, this returns null, instead of the id. I think Sequel should handle that case and issue another select to get the id or the full record when null is returned, don't you think?

Have a great weekend!

**Comment by jeremyevans** [comment]
I don't think the behavior you are describing is possible in Sequel's default configuration.  If I had to guess, you have `raise_on_save_failure = false` and a unique validation.  `find_or_create`is basically `find || create`.  So if the `find` returns nil, `create` is called.  Sequel by default raises an exception if `create` fails due to a validation error, but if you have `raise_on_save_failure =  false`, the exception is swallowed an nil is returned.  Best practice in Sequel development is to leave the default setting of `raise_on_save_failure = true`.

You may be able do to:

```ruby
class Sequel::Model
  def self.find_or_create(*a)
    super || find(*a)
  end
end
```

There are still cases where that can fail, but it's pretty unlikely unless deletions directly after inserts are happening.

In any case, I don't think this is a bug.  If you think it is or my guess is not correct, please reply with a minimal self-contained reproducible example showing the problem.

**Comment by rosenfeld** [comment]
`raise_on_save_failure` indeed is set to false, and the unique validation indeed exists.

If I understood it correctly, when `raise_on_save_failure` is false, the insert statement will be changed to use insert-select. I thought Sequel would rescue the exception without changing the insert statement with that option. At least now I understand what happened. `find` returned nil, then `create` returned nil because of `raise_on_save_failure` being false. In that case, I agree that replacing `find_or_create` as you suggested would fix it. I just need to better understand whether or not this is the right action to do for such cases. It's more likely I'll handle them separately now. I was just confused that find_or_create could return nil, but know I understand the reason and will look for the best way to handle those cases. Thanks.

**Comment by rosenfeld** [comment]
I decided to raise `Sequel::UniqueConstraintViolation` so that the transaction would be retried in that case.
