### ISSUE TITLE
Modern ruby slight incompatibility

### ISSUE THREAD

**Issue by pyromaniac** [jeremyevans/sequel#1375]
Hey, did you know?

```ruby
def foo(*a, **b)
  p a
end

foo(City.order(:id))
```

If you will pass a dataset to a method with such a signature, it will be converted to a hash with ids as keys and records as values. `foo(City.order(:id), {})` works as planned.

**Comment by barthez** [comment]
This is because of sequel dataset implements `to_hash` method. Ruby asks for `to_hash` method while it tried to match `kwargs`, and apparently, it tried to match `kwargs` first. Then argument respond to `to_hash` `kwargs` argument is being assigned with `argument.to_hash`.

**Comment by janko-m** [comment]
Implicit conversion methods like `#to_hash`, `#to_ary`, `#to_str`, `#to_int` etc. (as opposed to their *explicit* counterparts `#to_h`, `#to_a`, `#to_s`, `#to_i` etc) should ideally be implemented only by objects that really act like the corresponding object. For example, it makes sense for `ActiveSupport::HashWithIndifferentAccess` to implement `#to_hash`, because it really acts as a hash.

However, I don't think that it makes sense for `Sequel::Dataset` to implement `#to_hash`, because it isn't an object that acts like a hash. Even if we look at evaluating a `Sequel::Dataset` object, the result object is an *array*, not a hash. But I don't feel too strongly about it, as that would break backwards compatibility, so I support whichever decision is made. It's just that in retrospective it would be better if another name was chosen, one which doesn't mean anything to Ruby.

**Comment by jeremyevans** [comment]
`Sequel::Dataset#to_hash` existed before keyword arguments and I believe before ruby used `to_hash` as an implicit conversion method.  The interaction with keyword arguments is unfortunate, but unavoidable without breaking backwards compatibility.  I suppose we could alias `to_hash` to something else, and then you could undef `to_hash` to avoid this issue.  Any ideas for a possible method name?

**Comment by pyromaniac** [comment]
`to_map` comes to my mind first of all. `ids_hash`. What was the purpose of the method btw? It is basically `index_by(&:id)` and nothing else, right? `ids_index`?

**Comment by jeremyevans** [comment]
`to_hash` is used creating a hash using the given key and value column(s)
 (http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-to_hash).  For model datasets, this is extended so that you can call the method without arguments, in which case it will create an hash with keys being primary key values and values being the model instances.

**Comment by jeremyevans** [comment]
The `to_hash` method isn't specific to ids/primary keys, and the class used is Hash and not Map, so method names with `map` or `id` don't really fit.  `to_h` is a possible method name, and kind of makes sense, but `Enumerable#to_h` is already defined in ruby 2.4 and operates differently. 

Currently, the best method name I can come up with is `as_hash`.  `as_hash` is not currently used, makes reasonable semantic sense, and isn't too long.  I'm still open to other method names for a few days, so please post here if you have a different suggestion.

**Comment by pyromaniac** [comment]
`as_hash` sounds good enough as for me.

**Comment by art-solopov** [comment]
I just want to chip in and say that this bit of behaviour has caused me a bit of trouble paired with dry-auto_inject: https://github.com/trailblazer/reform/issues/455

Apparently, if you have a class that receives a single `Sequel::Model` object in the initializer and includes a [dry-auto_inject container](http://dry-rb.org/gems/dry-auto_inject/basic-usage/), it converts the object into hash, sometimes with unfortunate consequences.
