### ISSUE TITLE
Update 'Sequel' gem caused deprecation warnings.

### ISSUE THREAD

**Issue by affan00** [jeremyevans/sequel#1376]
I have updated sequel gem to its latest version 4.47.0, It gives deprecated method warnings like,

`SEQUEL DEPRECATION WARNING: Setting a model class dataset to an invalid dataset is deprecated and will be removed in Sequel 5.  Either use a valid dataset or set require_valid_table = false for the model class.`

`SEQUEL DEPRECATION WARNING: Sequel::Model.def_dataset_method is deprecated and will be removed in Sequel 5.  Define the method inside a dataset_module block, or use the def_dataset_method_plugin.`

**Comment by rennex** [comment]
Those warnings are meant to help you to change your code, so that it would keep working in the future.

From the changelogs of 4.47.0 and 4.46.0: 

> Setting an invalid dataset for a model is now deprecated. Historically, Sequel has swallowed exceptions for this to keep backwards compatibility, but it generally just results in code breaking later.

> Model.def_dataset_method and Model.subset have been deprecated by default, with support moved to the def_dataset_method plugin. It's been recommended for many years to use Model.dataset_module to define dataset methods, instead of calling def_dataset_method and subset on the model class.

**Comment by jeremyevans** [comment]
Correct, this is expected behavior, designed to help you fix your code, not a bug.  If you don't want to make the necessary changes, stay on an older Sequel version.

**Comment by ababich** [comment]
Can you please help (any hint) how to debug this, e.g. how to find which exactly model is problematic?

```
> rake db:drop db:create db:migrate

gems/sequel-4.47.0/lib/sequel/model/base.rb:992:in `rescue in check_non_connection_error'
gems/sequel-4.47.0/lib/sequel/model/base.rb:985:in `check_non_connection_error'
gems/sequel-4.47.0/lib/sequel/model/base.rb:1106:in `block in get_db_schema'
gems/sequel-4.47.0/lib/sequel/model/base.rb:1139:in `get_db_schema'
gems/sequel-4.47.0/lib/sequel/model/base.rb:878:in `set_dataset'
gems/sequel-4.47.0/lib/sequel/model/base.rb:689:in `inherited'
app/models/user.rb:3:in `<top (required)>'
gems/activesupport-5.1.2/lib/active_support/dependencies.rb:476:in `load'
gems/activesupport-5.1.2/lib/active_support/dependencies.rb:476:in `block in load_file'
gems/activesupport-5.1.2/lib/active_support/dependencies.rb:661:in `new_constants_in'
```

Looks like model `User` has a problem, but I'm a bit more than 100% sure that this model exists and is properly defined

**Comment by jeremyevans** [comment]
@ababich this comment doesn't appear to be related to the issue.  Second, you shouldn't be loading your models when migrating, as that is often the cause of bugs. Third, the rake tasks are not defined by Sequel, so you should probably ask for support from whatever project is providing the rake tasks.

**Comment by ababich** [comment]
@jeremyevans hmm.. but
1. this is exactly the same error as from the topic starter
2. I'm loading my models during migrations because I need to, and I **not** loading model in the same migration when it is created
3. this error is not related to rake, it is clearly thrown by Sequel

**Comment by jeremyevans** [comment]
@ababich You didn't show the deprecation warning in your comment, so there was no evidence provided that indicated it was the same issue.

In any case, you are asking for help on how to use Sequel, not reporting a bug in Sequel, so please use the sequel-talk Google Group or IRC to do that, as specified in the contribution guidelines.  However, you should isolate the issue to something that happens in pure Sequel (outside of Rails) before asking for support.

**Comment by janko-m** [comment]
@ababch It's not the same error, and what the issue author reported wasn't actually even an error, he reported a deprecation warning.

You should never need to load models in migrations. Using models in migrations is dangerous, because models can change over time, which means that the same migration file can have different behaviour depending on the time it is run.

If the error is coming from Sequel, that doesn't automatically mean that the bug is in Sequel. For example, if I call a Sequel method and pass a nil instead of an argument, Sequel might raise an error at some point in the execution, but the bug is still in my code, not in Sequel code.

**Comment by ababich** [comment]
Ok, same deprecation warning, not error
I do not feel that wording change helps to resolve

4.46 -> 4.47 started to show misleading and incorrect message that my model has `invalid dataset` definition.

This message should be fixed. In 4.47 changes I see that previously similar message very likely was suppressed

What's more, it is clear that this message appears only while migrations run.

What's more warning message is not saying that `Using models in migrations is dangerous` which is theoretically true but practically not applicable in my case

Warning message says **incorrect** and **misleading** information in particular, reproducible situation. I just reported it because it may confuse a lot of other users when they do migrations

**Comment by jeremyevans** [comment]
I don't think it will confuse many other users doing migrations, considering that most Sequel users do not use models in migrations, as it is a bad practice and Sequel's documentation warns against it.

The deprecation warning was added to make it easier for users to find errors in their code.  As the deprecation warning states, you can use the require_valid_table setting to turn off the deprecation warning and allow your code to continue to work in Sequel 5.

The deprecation warning is not misleading or incorrect.  At the time you created the model, the dataset was invalid, hence the warning.  Sequel does not know that you plan created the table the model's dataset references after the model was created.  If you do allow model creation with an invalid dataset, and later create the table the dataset references, you actually create a model that is quite broken, as it does not define the appropriate getter and setter methods for attributes.

**Comment by ababich** [comment]
Thanks! From you explanation it look like all migrations are being loaded at once and it does not matter if table was created in migration 1 while model invocation is in migration 2?

**Comment by jeremyevans** [comment]
When the migration files are loaded is not important.  What is important is that you do not load any model file until after the migration that creates/alters the model's table has been run.  As a best practice, your migrations should not reference your models at all.  Sequel does not load model files in migrations if you use `bin/sequel -m` to run the migrations.  You are using a rake task that is probably provided by your rails integration library, in which case you should file a bug in the bug tracker for that library, instead of posting in this bug tracker.

**Comment by ababich** [comment]
But this is the thing - dataset creation is in migration A and model call is in migration B (which is like 20migrations later because order of migrations is guaranteed)

So, if you think that `sequel` has nothing to do with this, I will try to figure out with `rake`

**Comment by jeremyevans** [comment]
@ababich As I've confirmed numerous times in previous comments, this is not a bug in Sequel.  Please refrain from posting additional comments on this issue.

**Comment by PedroVinicius** [comment]
Hey Jeremy! I'm seeing the same warning messages previously reported. I know isn't a bug, but what exactly should I change in my code?

**Comment by jeremyevans** [comment]
@PedroVinicius you should probably ask on the sequel-talk Google Group, providing a minimal self-contained example showing the problem.

**Comment by PedroVinicius** [comment]
I'll do that. Thanks! :wink:
