### ISSUE TITLE
subset_conditions does not work on dataset_module.

### ISSUE THREAD

**Issue by ayghor** [jeremyevans/sequel#1383]
### Complete Description of Issue

we should call `subset` or `where` inside teh `dataset_module`, not model class. _subset_conditions_ plugin still define methods on model class and not on `dataset_module`, causing name error.

### Simplest Possible Self-Contained Example Showing the Bug

```
require 'sequel'

DB = Sequel.sqlite

# create an items table
DB.create_table :satans do
  primary_key :id
  Integer :num
end

class Satan < Sequel::Model
  plugin :subset_conditions

  dataset_module do
    subset(:whole_satan, num: 666)
    subset(:half_satan, num: 333)
    subset(:satan, whole_satan_conditions | half_satan_conditions)
  end
end

Satan.create(num: 666)
Satan.create(num: 333)
Satan.create(num: 111)

puts Satan.satan.count
```
this works if you call teh last `subset` outside `dataset_module` or use `Satan.whole_satan_conditions` and `Satan.half_satan_conditions`. but not _as-is_

### Full Backtrace of Exception (if any)

```
$ ruby a.rb
a.rb:17:in `block in <class:Satan>': undefined local variable or method `whole_satan_conditions' for #<#<Class:0x0056441d0c1658>:0x0056441d0c1400> (NameError)
        from /home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/base.rb:357:in `module_eval'
        from /home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/base.rb:357:in `dataset_module'
        from a.rb:14:in `<class:Satan>'
        from a.rb:11:in `<main>'
```

<3

**Comment by jeremyevans** [comment]
This is expected behavior. The *_conditions methods are defined on the model's dataset, not on the dataset module, and model methods are created because the dataset methods were added.  I don't think the code you gave worked in a previous version.

It's true that moving the lines from outside dataset_module to inside dataset_module will result in breakage, but that was also true in previous versions, and will be true in any case where you are calling class methods to provide arguments to subset, it's not limited to the subset_conditions plugin.

If you want to keep the previous code, just use the def_dataset_method plugin and leave the subset calls outside of dataset_module.

**Comment by ayghor** [comment]
this never worked in previous versions. i just thought it should after teh deprecation warning to use `subset()` inside `dataset_module`.

**Comment by ayghor** [comment]
i mean: i thought teh plugin was so that we could reuse conditions on other dataset methods, liek `subset()`. teh way it is, it can, but is more cumbersome...

**Comment by jeremyevans** [comment]
If you want to reuse such data inside dataset_module, just use a local variable:

```ruby

class Satan < Sequel::Model
  plugin :subset_conditions

  dataset_module do
    ws =  {num: 666}
    hs = {num: 333}
    subset(:whole_satan, ws)
    subset(:half_satan, hs)
    subset(:satan, Sequel.|(ws, hs))
  end
end
```
