### ISSUE TITLE
Sequel::Dataset#multi_insert_sql would be same input like Sequel::Dataset#multi_insert

### ISSUE THREAD

**Issue by deepj** [jeremyevans/sequel#1398]
### Complete Description of Issue

`Sequel::Dataset#multi_insert_sql` would be same input like `Sequel::Dataset#multi_insert`.

### Simplest Possible Self-Contained Example Showing the Bug

For `#multi_insert` I need just call something like this

```ruby
DB['table'].multi_insert(records)
```

But for `#multi_insert_sql` I have to do something like this

```ruby
DB['table'].multi_insert_sql(records.first.keys, records.map(&:values))
```

Personally, I'd except same way of giving input in both cases. I understand these methods as equivalents. `#multi_insert_sql` just only returns given SQL query.

**Comment by jeremyevans** [comment]
`multi_insert` is just a wrapper for `import`, and `import` calls `multi_insert_sql` (indirectly through `_import`).  The historical reason for the naming is that `import` and `multi_insert` were previously aliases.  So `multi_insert_sql`'s API is similar to `import`'s API.

Since it's introduction in Sequel 1.1, `multi_insert_sql` has always taken an array of keys and an array of arrays of values, even when `multi_insert` just took an array of hashes: https://github.com/jeremyevans/sequel/commit/6c9fe154c41c922f0c6cf1ed8c4bce185d8a0099#diff-cce64bd259af70160e64cd9fefca5303R361

Despite the naming similarity, `multi_insert` and `multi_insert_sql` are not equivalents, and there are cases where `multi_insert` will not call `multi_insert_sql`.  In any case, this isn't a bug, so it can be closed.

**Comment by deepj** [comment]
@jeremyevans Hi Jeremy, I apologize for the late answer.

You might take a step back and don't see it through internal lens. There are other methods which have `_sql` suffix. But they takes the same arguments like their non-suffixed companions. I'd expect API have the same behavior for these methods. I was a bit badly surprised by `multi_insert` vs `multi_insert_sql`. I'd prefer a consistency of API.

Is it possible to unite a behavior of these two methods in Sequel 5?

**Comment by jeremyevans** [comment]
Yes, it is possible, and not a difficult change to make.  However, I'm not going to break backwards compatible for `multi_insert_sql` just so it takes the same arguments as `multi_insert`.  Feel free to do that via an external extension.

**Comment by deepj** [comment]
@jeremyevans Well, I still disagree. I thought it's always better have consistent and coherent API before keeping backwards compatibility. Just my 2 cents
