### ISSUE TITLE
What's the replacement for db=?

### ISSUE THREAD

**Issue by bobber205** [jeremyevans/sequel#1402]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
Getting this deprecation warning
`SEQUEL DEPRECATION WARNING: Sequel::Model.db= when the model has an existing dataset is deprecated and will be removed in Sequel 5.  Use Sequel::Model.dataset= instead.`

### Simplest Possible Self-Contained Example Showing the Bug
Just use `db=` in the newest version of the 4.x branch

I've scoured the documentation and I can't find a replacement for setting the db connector instance.
What should I use?

**Comment by jeremyevans** [comment]
As the deprecation message states, use dataset= instead of db=.  So if you were doing:

```ruby
class Artist < Sequel::Model
  self.db = DB2
end
```

switch to:

```ruby
class Artist < Sequel::Model
  self.dataset = DB2[:artists]
end
```

or even better:

```ruby
class Artist < Sequel::Model(DB2)
end
```

Also, as stated in the contribution guidelines and at the top of the issue template, do not use GitHub Issues to ask for help or for general questions regarding Sequel, only for reporting bugs.  Use the sequel-talk Google Group or IRC for help or general questions.
