### ISSUE TITLE
Less noisy logs

### ISSUE THREAD

**Issue by pronoiac** [jeremyevans/sequel#1406]
### Complete Description of Issue
We've noticed a *lot* of `SELECT NULL` entries in our logs. They're not particularly useful or informative. Could there be a way to turn these off?

### Full Backtrace of Exception (if any)
The function causing the noise is `valid_connection?` in `sequel/database/connecting.rb`.

cc @baguasquirrel

**Comment by jeremyevans** [comment]
You may be using the connection_validator extension with a low validation timeout.   You can use a custom logger that filters these entries out, but Sequel by design logs all queries sent to the database, even ones you may not think are important.  So you need to change your logger, not Sequel, in order to get the result you want.

As mentioned in the contribution guidelines, since this a question about how to use Sequel instead of a bug report, the sequel-talk Google Group and IRC are the appropriate support forums, so you should consider using those instead of filing an issue on GitHub in the future.
