### ISSUE TITLE
Warnings with schema_dumper

### ISSUE THREAD

**Issue by sandelius** [jeremyevans/sequel#1408]
Hello,

I was trying out the `schema_dumper` plugin and it gives me two warnings.

```
sequel/extensions/eval_inspect.rb:68: warning: method redefined; discarding old inspect
sequel/sql.rb:148: warning: previous definition of inspect was here
```

Not sure if this is considered a "bug" tho.

Thanks for your work with Sequel and in the Ruby community in general. 

/ Tobias

**Comment by jeremyevans** [comment]
Not a bug, and Sequel by design is not verbose warning free.  The good news is on ruby 2.4+ you can filter warnings.  There is even a warning gem that makes this easy:

```ruby
require 'warning'
Warning.ignore(:method_redefined)
```

Trying to avoid this particular warning is a bad idea, since there is not really a good way to atomically replace a method in ruby without it.  `remove_method` before defining the new method leaves a period where there is no method defined, which is especially bad in threaded situations.  You could use `prepend`, but Sequel currently works on ruby 1.9, and in general introducing additional unnecessary modules to work around verbose warnings is a bad idea.
