### ISSUE TITLE
Bignum alternatives for 2.4+

### ISSUE THREAD

**Issue by TPei** [jeremyevans/sequel#1433]
Hey,

I was wondering about how to handle the creation of a Bigint SQL columns, now that Bignum has been deprecated with ruby 2.4. Is there already something one could use in its place?

**Comment by jeremyevans** [comment]
You use the `:Bignum` symbol instead of the `Bignum` constant reference.  This is explained in http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-Column+types

As mentioned in the contribution guidelines, you should use IRC or the Google Group if you have questions about Sequel or need help using it.  You should only post on GitHub Issues if you are reporting a bug in the library.

**Comment by TPei** [comment]
Interestingly, using :Bignum causes a mysql  error when migrating:
```
Sequel.migration do
  up do
    add_column :users, :finished_field_of_study, :Bignum
  end

  down do
    drop_column :users, :finished_field_of_study, :Bignum
  end
end
```

causes
> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Bignum' at line 1

Using :Bigint works as expected. This somewhat contrasts the documentation, which says
> If a symbol or string is used as the type, it is used verbatim as the type name in SQL, with the exception of :Bignum. Using the symbol :Bignum as a type will use the appropriate 64-bit integer type for the database you are using.

**Comment by jeremyevans** [comment]
What version of Sequel are you using?  Please try with the latest version and if you can reproduce, submit a full backtrace and SQL log.
