### ISSUE TITLE
count method error ORA-02287 when sql is getting nextval

### ISSUE THREAD

**Issue by MarioRuiz** [jeremyevans/sequel#1440]
When running the sql "SELECT SEQ_myTable.NEXTVAL myId FROM dual" storing the result on a variable... 'result', If I call the method 'count' should return 1 but returns this:
 OCIError: ORA-02287: sequence number not allowed here

**Comment by jeremyevans** [comment]
It sounds like you are doing something like:

```ruby
DB["SELECT SEQ_myTable.NEXTVAL myId FROM dual"].count
```

Which doesn't really make sense to me.

For questions like this (e.g. why isn't this code working?), post them on the sequel-talk Google Group or IRC, not GitHub Issues, as instructed by the contribution guidelines.

In the future, please respect the contribution guidelines and only post a GitHub issue if you are sure the bug is in Sequel itself and not in your code.  Make sure to include a minimal self-contained example showing the error when submitting the issue.  See self-contained examples I posted in #1438 if you are not sure what a minimal self-contained example looks like.  If you cannot create a minimal self-contained example showing the issue, then you probably should assume it is not a bug in Sequel and therefore not post an issue.

**Comment by MarioRuiz** [comment]
I know it doesn't make sense because in this case we know in advance that will be one record but the code my app is using is generic and in some cases the sql statement is like that one... and it is not possible to know in advance which sql statement is going to be run and I need to know how many records are return... for that we use 'count' in this case should return '1' because it is just one record but instead is returning error.
I didn't add a more explained example since it is a very simple case, for next time i'll take it in consideration.
I solved this bug in my code witha begin rescue but it is not nice at all, once again I think that res.count should return always the number of records even when is one or obvious.

**Comment by jeremyevans** [comment]
As you can see from the exception (`OCIError: ORA-02287`), this error is raised by the Oracle database, not Sequel.  So if you think Oracle should not raise an exception for this, you should probably talk to them.

**Comment by MarioRuiz** [comment]
So... it is a misunderstanding.. i thouht when you were calling the fetch method on sequel, the result was managed by sequel... anyway thank you and sorry for your time
