### ISSUE TITLE
Update of sequel of 4 to 5 generates error in the pagination extension

### ISSUE THREAD

**Issue by CharlyJazz** [jeremyevans/sequel#1442]
### Description

The pagination extension worked fine until i updated sequel and now it does not to load the extension

The code has always been:

`DB.extension (:pagination)`

The error appears when this code is executed:

`page = Snippet.dataset.paginate (params [: page] .to_i, 4)
`
### Exception

**2017-10-24 14:06:22 - NoMethodError - undefined method 'paginate' for #<Sequel::SQLite::Dataset: "SELECT * FROM \`snippets\`">:**

**Comment by jeremyevans** [comment]
I can't recreate this error using the following self-contained example:

```ruby
DB.extension(:pagination)
DB.create_table(:snippets){primary_key :id}
class Snippet < Sequel::Model; end
Snippet.create
page = Snippet.dataset.paginate(1, 4)
page.all
```

Your issue report is incomplete, so I'm left to guess as to why your code stopped working after the upgrade.  If I had to guess, you are adding the extension to the database after creating the model class instead of before, but that's only one possible cause.

If you still think this is a bug in Sequel, please submit a self-contained example showing the problem (similar to the example above), as specified in the contribution guidelines and as shown in the issue template.  If you are not able to create a self-contained example showing the problem, you should assume the bug is in your code and not in Sequel.

**Comment by CharlyJazz** [comment]
> "If I had to guess, you are adding the extension to the database after creating the model class instead of before, but that's only one possible cause."

Correct that was the problem.

**Comment by jeremyevans** [comment]
OK.  This can be closed, as it is expected behavior.  The code order guide already documents that extensions should be loaded before model classes, so I don't think additional documentation changes are necessary.
