### ISSUE TITLE
Expression problem...

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1454]
I'm having a strange issue with expressions... I'm trying to return all 'SearchQueue' items with a last_scan (DateTime) value of either nil or later than a day ago. At the moment, all of my SearchQueue items have a last_scan value of nil.

If I do `puts SearchQueue.where{(last_scan < Time.now - 24*60*60) | (last_scan = nil)}` I get nothing returned.

However, `puts SearchQueue.where{last_scan = nil}` returns all of SearchQueue items, as it should.

Unless I'm missing something, I believe this is a bug of some sort. I'm following the example from the documentation, so there's no reason this shouldn't be working...

(Documentation shows: `Artist.where{(a > 1) & ~((b(c) < 1) | d)}`)

**Comment by jeremyevans** [comment]
This isn't a bug.  You want `{:last_scan=>nil}` or `(last_scan =~ nil)` instead of `(last_scan - nil)`.  `(last_scan = nil)` is just a local variable assignment.

There may be a bug here, in that `where{last_scan = nil}` should be the same as `where(nil)`, and should use `WHERE NULL` instead of omitting the `WHERE` clause.  It looks like there were no tests at all for that, and it didn't get caught in the upgrade to Sequel 5.  As fixing that would change existing behavior, I'll need to deprecate the current behavior before putting in a fix.
