### ISSUE TITLE
Query returns wrong timestamp from Postgresql

### ISSUE THREAD

**Issue by kaikuchn** [jeremyevans/sequel#1455]
### Complete Description of Issue

PostgreSQL stores timestamps without timezone, which are then assumed to be in UTC by consumers. However, Ruby parses timestamps without timezone in local time. This leads to a bug when a timestamp is stored where the period does not exist in the local timezone.
E.g., in central Europe the DST period began on the 26th of March 2017 at 1 a.m. UTC (clocks were shifted forward by one hour). Thus `2017-03-26 02:30:00` is not a valid local time for central Europe. When querying such a timestamp through sequel, the resulting time object is off by one hour.

The reasons is that we cannot simply parse the timestamp string without adding time zone information and then ignore the offset since this would happen:

```ruby
Time.parse('2017-03-26 02:30:00')
=> 2017-03-26 03:30:00 +0200
```

Had we added timezone information, we would get the expected output and could safely ignore the offset:

```ruby
Time.parse('2017-03-26 02:30:00'+?Z)
=> 2017-03-26 02:30:00 UTC
```

### Simplest Possible Self-Contained Example Showing the Bug

This depends highly on your local timezone, for central europe the below works. Adapt the timestamp as necessary for your local zone, it must be one that does not exist!
```ruby
Sequel.default_timezone = :utc
db = Sequel.connect('postgresql://localhost/postgres')
db["select '2017-03-26 02:30:00'::timestamp"].to_a
=> [{:timestamp=>2017-03-26 03:30:00 UTC}]
```

@jeremyevans in your github profile it says that you live in Sacramento, for your convenience, this should reproduce correctly on your machine:

```ruby
Sequel.default_timezone = :utc
db = Sequel.connect('postgresql://localhost/postgres')
db["select '2017-03-12 02:30:00'::timestamp"].to_a
```

This bug was first noticed [here](https://github.com/hanami/model/issues/469).

Edit @2017-11-30 17:07:24 UTC: Clarified the description according to comments.

**Comment by jeremyevans** [comment]
This statement is not correct: `Postgresql stores timestamps without timezone in UTC`.  PostgreSQL stores `timestamp` without any timezone information at all.  For `timestamp with timezone`, it converts the input value to UTC and stores it, and on output converts the value to the timezone of the connection.  See https://www.postgresql.org/docs/10/static/datatype-datetime.html

If you want sane behavior in multiple timezones, you should be using `timestamp with timezone` type.

If you want to change which timezone Sequel will use for timestamps without timezone information, you can set `Database#timezone`:

```ruby
DB.timezone = :utc
DB["select '2017-03-12 02:30:00'::timestamp"].to_a
# => [{:timestamp=>2017-03-12 02:30:00 UTC}]
```

I don't think this is a bug in Sequel.  If you still think it is a bug, please explain what you think the correct behavior should be.  I don't think the correct behavior is assuming UTC if not explicitly configured that way, and Sequel already offers a way to configure the implicit timezone.

**Comment by kaikuchn** [comment]
You're right, what I mean is that the assumption by the application is that those timestamps are in UTC.
I've just noticed that one can configure the timezones in sequel, and added that to the description.
I'd assume that it is a bug since

```ruby
Sequel.default_timezone = :utc
db = Sequel.connect('postgresql://localhost/postgres')
db["select '2017-03-26 02:30:00'::timestamp"].to_a
=> [{:timestamp=>2017-03-26 03:30:00 UTC}]
```

Should have returned `[{:timestamp=>2017-03-26 02:30:00 UTC}]` instead.

**Comment by jeremyevans** [comment]
FWIW, Sequel 4 is unsupported.  Only the master branch and the latest release are supported.  I don't think the current behavior is different though.

I can recreate your issue if I set `TZ=Europe/Berlin`.  This conversion of `2:30` to `3:30` is done by ruby in `Time.parse`, it's not something Sequel is doing.  We would have to stop calling `Time.parse`, or manually monkey with the string before calling `Time.parse`, neither of which I want to do by default as it is is likely break other things.

I can support this via an extension so that instead of calling `Time.parse`, we call `DateTime.parse.to_time`.  `DateTime` defaults to UTC if an offset is not given, and calling `to_time` on that results in a time in UTC. That won't make the release of 5.3.0 tomorrow as the integration testing for that is almost complete, but I can commit it before 5.4.0.

**Comment by kaikuchn** [comment]
That matches with what I suspected to be going on!
We'll probably have to monkey patch then until we get around to updating to the latest sequel version.

I assume that always using `DateTime` parse would break behaviour when using `local` as the timezone (`Sequel.default_timezone = :local`). But I'm not sure about that, since I haven't been able to pinpoint where exactly conversion happens.
Can you maybe point me in the right direction?

Thanks,
Kai

**Comment by jeremyevans** [comment]
The extension will need to handle that case, since other code in Sequel assumes `Sequel.string_to_datetime`  results in a local timestamp if datetime_class is Time and no input timezone is given.  I'm assuming if `Sequel.application_timezone = :local`, we can just call `localtime` on the result of `DateTime.parse.to_time` to make sure the returned time is in local time.
