### ISSUE TITLE
Under JDBC/PostgreSQL, non-null money column -> DatabaseError

### ISSUE THREAD

**Issue by andy-twosticks** [jeremyevans/sequel#1458]
Hi,

re: #1257 -- under Sequel 5.3 the workaround you furnished now fails to work because we append to  Sequel::JDBC::Postgres::Dataset::PG_SPECIFIC_TYPES, which is of course now frozen.  (Please see that issue for details.)

I'm afraid I still don't see a way around this, other than removing the money columns in my application or picking up the money value string from the error message telling me that it's not a Double (and understandably, I think, I don't like either of those options.)

Is there any way I can persuade Sequel to return a value from a Money column under the combination Sequel 5 / JDBC / JRuby / Pounds Sterling?

**Comment by jeremyevans** [comment]
The problem here is that the PostgreSQL JDBC driver uses the incorrect type `java.sql.Types.DOUBLE` for money.  The fact that is the wrong type should be obvious since `ToDouble` raises an exception for it. `java.sql.Types.OTHER` should be used instead.

This is not a bug in Sequel, it's a bug in the upstream driver, so get them to fix the bug upstream.

In terms of working around the problem in Sequel, you just need a slight modification to the code I showed in #1257:

```ruby
c = Sequel::JDBC::Postgres::Dataset
vals = c::PG_SPECIFIC_TYPES + [Java::JavaSQL::Types::DOUBLE]
c.send(:remove_const, :PG_SPECIFIC_TYPES)
c::PG_SPECIFIC_TYPES = vals.freeze
DB.add_conversion_proc(790){|s| s}
```

**Comment by andy-twosticks** [comment]
I don't hold out much hope for getting this fixed upstream since as you pointed out the last time, they opened and closed a ticket for this matter quite a while ago.  I'll try raising a new ticket on Friday, though.

Thanks for pulling my arse out of the fire again!  `send(:remove_const)`, eh? You learn something new every day...
