### ISSUE TITLE
Preliminary: DB2 adapter (shared) claims TIMESTAMP does not support microseconds

### ISSUE THREAD

**Issue by guyboertje** [jeremyevans/sequel#1463]
### Complete Description of Issue

In Logstash we use Sequel in the JDBC Input plugin to ingest db records. One user has reported that the SQL statement logged after the properties are merged into the statement is missing milliseconds. The property being merged is a Ruby Time instance.
The relevant part of the statement as logged is `WHERE fechahora > '2017-12-18 23:49:59'`
The user reports that due to the missing microseconds some records are ingested twice when `fechahora` is in the same second as the previous run.

[This line states](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/db2.rb#L349) that `DB2 does not support fractional seconds in timestamps` but I think it does, although I can't personally confirm it.

We are asking the user to change the flag from false to true in a staging environment and get back to us with the logged statement to confirm that the statement has microseconds and that the duplicate ingestion problem is fixed. When they do I will remove the Preliminary text in the subject line.

**Comment by jeremyevans** [comment]
From some research, it looks like the currently supported versions of DB2 do support fractional seconds in timestamps.  The disabling of fractional seconds has been there since the initial DB2 support was added, and it's possible I never tested it with it enabled.  So it should be fairly simple to flip that switch and run Sequel's tests to see if it breaks anything.

There are a wide variety of DB2 versions, and some of them are quite different in terms of what they support (z/OS compared to Unix/Linux).  I only have the ability to test the Unix/Linux version, so we should probably at least offer a way to disable the fractional seconds support via a Database option if it is turned on by default.

Note that DB2 time values do not appear to support fractional seconds, so that will need to be handled correctly.

**Comment by guyboertje** [comment]
Hi Jeremy,
Thanks for your reply. Upon reflection, an options switch is a suitable low risk solution IMO. We don't have many DB2 users so a switch with an article in our knowledge base should suffice.
