### ISSUE TITLE
defaults_setter doesn't work with pg_array

### ISSUE THREAD

**Issue by 7dr1v3** [jeremyevans/sequel#1466]
I'm using plugins defaults_setter and pg_array.
For boolean, integer, string, etc it works fine but with varchar_array (a type from pg_array) it just doesn't work.
If we look into Model.db_schema, we will see somthing like this 
```
{:oid=>1015, :db_type=>"character varying[]", :default=>"'{}'::character varying[]", :allow_null=>false, :primary_key=>false, :type=>:varchar_array, :ruby_default=>nil}
```
ruby_default is nil...

I think it is bug in pg_array or maybe this plugin is just not completed.

**Comment by jeremyevans** [comment]
This isn't a bug.  It isn't possible to parse all default values.  While the particular case of the empty array is probably feasible to handle, anything more complex probably is not, because then you end up trying to parse arbitrary SQL.

You can always override the default values that Sequel uses:

```ruby
Model.default_values[:column] = lambda{Sequel.pg_array([], 'character varying')}
```

Having the `pg_array` extension to try to integrate with the `defaults_setter` plugin would require storing a lambda as the value of the :ruby_default option, which I don't believe we have done before and may cause problems with code that relies on :ruby_default having actual values as opposed to callable objects.  Alternatively, the `defaults_setter` plugin would have to look for a different schema entry in preference to :ruby_default, and the `pg_array` extension would have to populate that.

**Comment by tycooon** [comment]
Why exactly do we need lambda for that value?

**Comment by jeremyevans** [comment]
Because presumably you don't want to have the same array used as the default for all objects.  I'm guessing you want a separate array created for each object.

After some more thought about this, another issue with trying to handle this automatically is that default values are not cached.  This would result in:

```ruby
model.array_column # => []
model.array_column  << 1
model.array_column # => []
```

In general you aren't supposed to mutate the default values, and as the default values are generally immutable that's fine.  When you introduce objects that are generally mutable such as arrays, you get problems.  It wouldn't make sense to introduce this without adding support to the `defaults_setter` plugin for caching the default values returned.

**Comment by 7dr1v3** [comment]
Why defaults_setter can't write values into model.values when we call Model.new ?

**Comment by jeremyevans** [comment]
There's no reason it can't, but it is less efficient and in general not necessary.

**Comment by jeremyevans** [comment]
Note that if you want to do that, it's trivial to do manually:

```ruby
def initialize(values={})
  super
  self[:array_column] = Sequel.pg_array([], 'character varying')
end
```

**Comment by 7dr1v3** [comment]
Well, our company active use sequel in our projects and we need this features. We can try to solve this and make pull request but only if after that you agree to set our company logo into readme on github as contributor. It is requirements of our company for open source.

**Comment by jeremyevans** [comment]
`need` is obviously the wrong word here.  The lack of array defaults being handled automatically is something trivial to work around.  That's not to say it isn't nice to have, and I plan to work on it before the next release.

In regards to the README, adding company logos is not and will never be acceptable.   Your company should change it's requirements in that case.  I'm surprised that any respectable open source project would agree to such a condition.  Note that contributors aren't listed on Sequel's README anyway.  For recognition, the submitter is listed in the git repository and CHANGELOG.

**Comment by tycooon** [comment]
Strings are mutable as well, but string default values are not using lambdas now, I guess. What's the difference?

**Comment by jeremyevans** [comment]
Strings are not generally mutated, whereas arrays usually are.  It wouldn't be a bad idea to freeze the strings used for default values to ensure they are not accidentally mutated, though.

**Comment by tycooon** [comment]
Maybe we can just use `dup` in defaults_setter (in case it's supported by the value).

**Comment by jeremyevans** [comment]
Using `dup` causes problems in cases where the object responds to `dup` but raises an exception if `dup` is called.  This is true for versions of ruby that Sequel still supports.

Calling `dup` is also less flexible that just supporting lambdas, which are already supported.

**Comment by scatmanoleg** [comment]
Hi @jeremyevans,
I want to apologize for the words about the company, logs and etc. This is not a requirement of our company and that is some our internal misunderstanding. 
@7dr1v3 is very good guy and great developer, but not so good in English :)

We are using Sequel in many our projects and we are grateful to you for your work.

We are going to discuss internally the PR for this feature, and if it gets merged, mention in CHANGELOG would be the best reward for us.
