### ISSUE TITLE
MySQL: select count distinct with multiple columns

### ISSUE THREAD

**Issue by cmrd-senya** [jeremyevans/sequel#1528]
I'm running into issue with using Sequel with MySQL. Sequel is 5.10.0 and MySQL is `mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper`.

My table contains two integer fields `month` and `year`

Here is the failing code:
```ruby
Sequel::Model.db[:table].select { count(distinct month, year) }.all
```

`select { count(distinct month, year) }` generates the following SQL:

```sql
SELECT count(distinct(`month`, `year`)) FROM `table` # fails
```

If you run this code using mysql CLI  it'll generate error:
```
Error Code: 1241. Operand should contain 1 column(s)
```

At the same time, if you run the SQL without brackets arount `distinct` arguments, it'll work:

```sql
SELECT count(distinct `month`, `year`) FROM `table` # works
```

So the following works:

```ruby
Sequel::Model.db[:table].select { Sequel.lit("count(distinct month, year)") }
```

I can use the latter as a workaround, but this behavior looks like a bug.

**Comment by jeremyevans** [comment]
This isn't a bug, you are specifying a nested function call instead of the DISTINCT modifier to the count function.  You want to use:

```ruby
Sequel::Model.db[:table].select { count(:month, :year).distinct }.all
# SELECT count(DISTINCT month, year) FROM table
```

See the following documentation for details:

http://sequel.jeremyevans.net/rdoc/files/doc/sql_rdoc.html#label-Aggregate+Functions
http://sequel.jeremyevans.net/rdoc/classes/Sequel/SQL/Function.html
