### ISSUE TITLE
Sequel serialization plugin save Time object to a json column not work as expect

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1564]
Following is my new added test file which should be describe all what i want:

My feed model file:

```rb
class Feed < Sequel::Model
  plugin :paranoid, enable_default_scope: true
  plugin :serialization, :json, :metadata
end
```

```rb
require 'test_helper'

class FeedTest < ActiveSupport::TestCase
  test 'Sequel 的 serialization 插件保存时间字符串出错?' do
    # Metadata is a serialization plugin column (MySQL2)
    feed = create(:feed, metadata: nil)
    assert_nil feed.reload.metadata

    # Update feed metadata success
    refute_nil feed.update(metadata: {'finished_at' => '2018-10-24 10:10:10 +0800'})

    # This is expected behavior.
    assert_equal '2018-10-24 10:10:10 +0800', feed.reload.metadata['finished_at']

    # create a time object
    time = Time.new(2018, 10, 24, 10, 10, 10)
    assert_equal '2018-10-24 10:10:10 +0800', time.to_s

    # Update feed metadata success
    refute_nil feed.reload.update(metadata: {'finished_at' => time})

    # What i expect is: save finished_at as '2018-10-24 10:10:10 +0800',
    # not '2018-10-24T10:10:10.000+08:00', where is this special format string come from?
    assert_equal '2018-10-24T10:10:10.000+08:00', feed.reload.metadata['finished_at']
  end
end

```

I try time with following format, no saved format.
```sh
(pry):#<FeedTest:0x000055851b97cac0>(0)> time.rfc2822
"Wed, 24 Oct 2018 02:10:10 -0000"
(pry):#<FeedTest:0x000055851b97cac0>(0)> time.rfc3339
"2018-10-24T02:10:10Z"
(pry):#<FeedTest:0x000055851b97cac0>(0)> time.rfc822
"Wed, 24 Oct 2018 02:10:10 -0000"
(pry):#<FeedTest:0x000055851b97cac0>(0)> time.iso8601
"2018-10-24T02:10:10Z"
(pry):#<FeedTest:0x000055851b97cac0>(0)> time.inspect
"2018-10-24 02:10:10 UTC"
```

**Comment by jeremyevans** [comment]
The format comes from ActiveSupport (not Sequel), if you don't like it, file a bug here: https://github.com/rails/rails/issues.  Alternatively, you could just not use ActiveSupport in your application.

```ruby
Time.now.to_s
# => "2018-10-25 06:55:03 -0700"
Time.now.to_json
# => "\"2018-10-25 06:55:08 -0700\""
require 'active_support/all'
# => true
Time.now.to_json
# => "\"2018-10-25T06:55:47.949-07:00\""
```

In the future, please follow the contribution guidelines and the bug report template, specifically the part about submitting a minimal self contained reproducible example.   Taking the time to create a self contained example for this bug report would have made it obvious that the problem was not in Sequel but in another library.  If you submit a bug report without a minimal self contained reproducible example in the future, it will probably be closed until such an example is provided.

In this particular issue, you aren't even reporting a bug, you are asking a question about why you got a certain output.  Almost any time your "bug report" is really a question (`where is this special format string come from?`), you should be asking the question on the sequel-talk Google Group or IRC, per the contribution guidelines. In the future, before you post a bug reports here, considering asking on the sequel-talk Google Group or IRC about whether the behavior is a bug.

**Comment by zw963** [comment]
@jeremyevans , OK,  i will follow bug report next time, Thanks very much.
