### ISSUE TITLE
Correctly loading :pg_enum in migration

### ISSUE THREAD

**Issue by grahamnoel** [jeremyevans/sequel#1579]
I'm having some issues interpreting the documentation for creating a pg_enum in a migration.

Following the docs at https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#using-database-extensions-in-migrations led me to create the following migration code:

```
Sequel.migration do
  change do
    extension :pg_enum

    create_enum(:enum_foobar, %w[foo bar])
  end
end
```

which throws a `Sequel::Error: irreversible migration method used` when trying to migrate down.

The advice given here: https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_enum_rb.html says to load the :pg_enum extension after the :migration extension, yet the example that follows this does not show how to do that. 

In any case, surely the above code achieves loading the extension last since the :pg_enum extension is loaded at the last possible moment within the change block itself.

Trial and error led me to find a _potential_ solution:

```
Sequel.extension :pg_enum

Sequel.migration do
  change do
    extension :pg_enum

    create_enum(:enum_foobar, %w[foo bar])
  end
end
```

Why is it required to load the extension twice? (removing the inner extension call throws an error `NoMethodError: undefined method create_enum`). 

Is there a better way of doing this that I'm missing? I did look at issue #1182 but again, no clear working example of usage was given.

Thanks!

**Comment by jeremyevans** [comment]
Thanks for the report.

Migration `change` blocks can't handle `extension` calls, so you need to load the `pg_enum` extension into the Database instance after loading the migration extension and before running the migration on the Database instance.  Code would be similar to this if you are using the migration API directly:

```ruby
DB = Sequel.connect('...')
Sequel.extension :migration
DB.extension :pg_enum
Sequel::Migrator.apply(DB, 'migrate', version)
```

If you are using bin/sequel to run the migrations, it would be similar to:

```
bin/sequel -m migrate -r ./migrate_setup connection_string
```

Where `migrate_setup.rb` contained:

```
Sequel.extension :migration
DB.extension :pg_enum
```

If you would like this added to the pg_enum extension documentation, please submit a pull request.

A simple work around would be to just use up/down blocks instead of change blocks for the migration.

**Comment by grahamnoel** [comment]
Cool, thanks for the additional info!
