### ISSUE TITLE
High memory usage with SQLite execute method

### ISSUE THREAD

**Issue by sosedoff** [jeremyevans/sequel#1616]
I've been profiling an application that was consuming large  amount of memory and pinned down the hot spot. It turned out to be the SQLite adapter, `execute` method in particular. 

I wasn't sure what was going on so i made a sample demo script to illustrate the problem:
https://gist.github.com/sosedoff/2471e6b0e8e11ebdf1f903137ab1303c

The script inserts 1M rows into the DB and uses 2 DB drivers: sqlite3 gem vs sequel. 
With sequel the script uses 1G+ ram vs ~40-50mb with sqlite3 (on OSX), and even lower (~30) on linux/amd64. 

- Test with Sequel gem: `ruby script.rb`
- Test with Sqite3 gem: `SQLITE3=1 ruby script.rb`

Environments tested, very similar results:

- OSX 10.14, MRI 2.5.5, sqlite3 homebrew package 3.27.1
- Ubuntu Linux 18.04, MRI 2.5.5
- Sqlite gem: 1.4.0
- Sequel gem: 5.19.0

Let me know if you know what might cause this or if you need extra details.

**Comment by jeremyevans** [comment]
Thanks for the report. This is not a bug or performance issue, it's a misuse of the API. You should not call `Sequel::Database#execute` directly with Sequel, it's an adapter dependent API, and on most adapters it is used for returning results.  On SQLite, Sequel calls `SQLite3::Database#query` if you call `Sequel::Database#execute`.  If you use `Sequel::Database#run` instead of `Sequel::Database#execute`, RAM usage doesn't increase.

**Comment by sosedoff** [comment]
Interesting, thanks for the quick reply. 

On the other hand, does that mean if result of `execute` call is not consumed it will create a memory leak?

**Comment by jeremyevans** [comment]
In normal Sequel usage for returning rows (`Dataset#each`), a block is passed to `SQLite3::Database#query`, and in that case SQLite3 doesn't leak memory. Here's some old documentation for ruby-sqlite3 regarding the behavior: `https://www.rubydoc.info/github/luislavena/sqlite3-ruby/SQLite3%2FDatabase:query`
