### ISSUE TITLE
Using single_table_inheritance, created object isn't correct subclass

### ISSUE THREAD

**Issue by thomasmarren** [jeremyevans/sequel#1624]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

When creating an object and assigning to a variable, the created object assigned to the variable is the base class Class instead of the subclass Class. The expectation is the created object would be of the subclass.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
class Experiment < Sequel::Model
  plugin :single_table_inheritance, :experiment_type, model_map: {'TEST' => :TestExperiment}
end

class TestExperiment < Experiment
end

Sequel::Model.db.transaction do
  experiment = Experiment.create(
    experiment_name: 'Name',
    experiment_type: 'TEST'
  )

  experiment.class
  => Experiment

  Experiment.first(experiment_id: experiment.experiment_id).class
  => TestExperiment
end
```

### Full Backtrace of Exception (if any)

N/A

### SQL Log (if any)

N/A

**Comment by jeremyevans** [comment]
My expected behavior of `create` is that it returns an instance of the receiver, and that is how Sequel::Model operates by default, and the single_table_inheritance plugin does not override `create`.

If you want a subclass instance, you have to refetch after `create`, as you did in your example.  You could also do:

```ruby
h = {
  experiment_name: 'Name',
  experiment_type: 'TEST'
}
(Experiment.sti_model_map[h[:experiment_type]] || Experiment).create(h)
```

If you want to avoid the refresh.
