### ISSUE TITLE
Anonymous class created with Model(:my_dataset) errors on #model_name

### ISSUE THREAD

**Issue by karlhe** [jeremyevans/sequel#1662]
### Complete Description of Issue

When defining a model in this manner:

```ruby
class MyModel < Sequel::Model(:my_dataset)
end
```

Sequel creates an anonymous class with `set_dataset(:my_dataset)`, then has MyModel inherit from this.

This usually works fine, but attempting to call `model_name` on this class will error.

We only noticed this because we extended Sequel::Model with ActiveModel::Translation (https://github.com/rails/rails/blob/master/activemodel/lib/active_model/translation.rb).

For example, trying to use `MyModel.human_attribute_name(:foo)` will fail because it iterates through `MyModel.ancestors` for anything where `responds_to?(:model_name)` returns true. The anonymous class (incorrectly?) returns true.

An easy workaround is calling `set_dataset` directly within the model when a custom dataset is desired.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
class MyClass < Sequel::Model(:my_dataset)
end
```

```bash
> MyClass.superclass.respond_to?(:model_name)
=> true
> MyClass.superclass.model_name
ArgumentError: Class name cannot be blank. You need to supply a name argument when anonymous class given
from /Users/karlhe/.gem/jruby/2.5.0/gems/activemodel-5.2.3/lib/active_model/naming.rb:151:in `initialize'
```

**Comment by jeremyevans** [comment]
`model_name` in this case is not defined by Sequel, it's defined by `ActiveModel::Naming`.  So if this is a bug, it is a bug in `ActiveModel::Naming`.  You may want to consider filing the bug upstream.  Note that if I was upstream, I wouldn't consider `responds_to?(:model_name)` being true as a bug, as the method is defined and the superclass does respond to it (raising an exception).  The real issue is something (`human_attribute_name`) iterating through ancestors looking for whether any ancestor responds to a method, and assuming that any method defined is safe to call.

If you want to work around the issue in Sequel, you can prevent the anonymous superclass by switching to:

```ruby
MyClass = Sequel::Model(:my_dataset)
class MyClass
end
```

**Comment by karlhe** [comment]
OK, that's fair. I actually just found the same issue dating back to Rails 3: https://github.com/rails/rails/issues/707

I'll probably use John's suggestion of overriding lookup_ancestors in the meantime.
