### ISSUE TITLE
Unexpected behaviour when using Ruby String for `:key` option in associations

### ISSUE THREAD

**Issue by gchan** [jeremyevans/sequel#1679]
### Complete Description of Issue
It appears the use of Ruby String as a value for the `:key` option in associations is inconsistent. The documentation suggests symbols should be used but it seems Strings appear to be semi-supported for some associations but not others. For others, the behaviour is unexpected. 

Does `sequel` support String for `:key` option? 

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
# Database schema:
#  nodes
#   :id        <--\
#   :ref_node_id ---/
#   :name

class Node
  many_to_one :parent, key: :ref_node_id, class: self # This work 
  many_to_one :parent2, key: "ref_node_id", class: self # This also works, but should it? 

  one_to_many :children, key: :ref_node_id, class: self # This works
  one_to_many :children2, key: :ref_that_doesnt_exist, class: self # This crashes as expected
  one_to_many :children3, key: "ref_node_id", class: self # This doesn't work or raise an error, calling .children3 will return an empty array
end

node.parent # => nil or instance of Node
node.parent2 # => nil or instance of Node

node.children # => Array of Node
node.children2 # => error
node.children3 # => always an empty Array, even though it should return associated Nodes
```

**Comment by jeremyevans** [comment]
The :key value should be a symbol as it represents an SQL identifier.  If you use a string, in most cases an SQL string will be used instead of an SQL identifier, as Sequel treats ruby strings as SQL strings.  So the behavior is expected from that perspective.  All of the documentation should show usage with a symbol (unless it is discussing more advanced usage with SQL expressions).  If you find a case in the documentation where a string is used as the :key value, please report that as a documentation bug.

**Comment by gchan** [comment]
Thanks for the explanation! So symbols should be used almost all of the time but Ruby strings are supported for advanced usage? And the difference in behaviour I describe above between `many_to_one` and `one_to_many` when using Ruby strings is the expected behaviour?

**Comment by jeremyevans** [comment]
Correct.  More precisely, in some cases the value of the option is used as a method name, and sometimes it is used as an SQL expression (this can be customized by other association options).  The difference in behavior is due to how the different associations and methods use the option.  More advanced usage of the `many_to_one` association, such as the use of eager_graph, would probably also result in an error.
