### ISSUE TITLE
[Documentation] Integrating Sequel to a Sinatra App

### ISSUE THREAD

**Issue by rubyFeedback** [jeremyevans/sequel#1702]
Hey Jeremy,

I know you like to keep the issues here tidy, so please feel free to close the issue here at any moment in time.

I have been using sinatra since about 2 years so far and I like it a lot more than Rails; mostly because I like to focus on small things, and move in baby steps from there, whereas rails forces me to understand a LOT before being able to move forward.

Anyway - different people recommend sequel - for example, recently here:

https://old.reddit.com/r/ruby/comments/hcgsb7/rails_vs_sinatra/

And I was thinking of the simplest path to integrate sequel into a sinatra app. But I am quite lazy too (sorry), so I was thinking of a primer; something that is not too long. 1-2 pages or so.

You already provide a lot of information here: http://sequel.jeremyevans.net/documentation.html

But no particular subsection with sinatra, and ideally with a few examples - just to get things started (I usually start reading the examples first, getting them to work, before I read documentation. No idea if others behave the same way or so).

Anyway, this is not meant to target specifically you - anyone else who may feel like writing 1-2 pages about this, a simple example really suffices. But as said, feel free to close this issue here at any moment in time - a clean issue tracker is a good thing.

**Comment by jeremyevans** [comment]
You are correct that no section of the documentation specifically discusses web frameworks (neither Sinatra, nor Rails, nor Roda).   This is sort of by design, for a couple reasons:

1. I don't want to have Sequel's documentation appear to endorse a particular web framework or frameworks.
2. (More importantly) You can setup Sequel exactly the same way no matter what framework you are using.  Just require, it, setup your Sequel::Database constant, create your model classes, etc..

When using Sinatra, you can setup Sequel pretty much anywhere in the application outside of one of your Sinatra routes.  When I used Sinatra, I would generally setup Sequel before requiring Sinatra and defining my Sinatra routes.  But you don't necessarily have to do it that way.  One of the advantages to using Sinatra or Roda compared to Rails is you more or less have the freedom to setup things the way that works best for you, as opposed to the way that works best for the framework.
