### ISSUE TITLE
String keys do not work for "where" query

### ISSUE THREAD

**Issue by alexey-klimuk** [jeremyevans/sequel#1715]
Hi there,
I'm running simple `where` query but it behaves differently for `string` and `symbol` keys.

### ENV
ruby 2.7.1
rails 6.0.3.2
sequel 5.22.0
pg 1.2.3

### Code
```ruby
class Section < Sequel::Model

end


> Section.where("position" => "21").count
=> 0 
> Section.where(position: "21").count
=> 1 
```

### SQL Log

```ruby
> Section.where("position" => "21").sql
=> "SELECT * FROM \"sections\" WHERE ('position' = '21')" 

> Section.where(position: "21").sql
=> "SELECT * FROM \"sections\" WHERE (\"position\" = '21')" 
```

**Comment by jeremyevans** [comment]
This is expected behavior.  In Sequel, Ruby symbols represent SQL identifiers and Ruby strings represent SQL strings.  Please review the Sequel documentation.  This is covered in the README (http://sequel.jeremyevans.net/rdoc/files/README_rdoc.html#label-Column+references+in+Sequel), and multiple other places.
