### ISSUE TITLE
Unique auto-validations are not inherited by subclasses when using CTI (others are)

### ISSUE THREAD

**Issue by benalavi** [jeremyevans/sequel#1747]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

When using the `auto_validations` plugin on the superclass of a CTI relationship subclasses will also run the same auto validations _except for_ uniqueness validations.

### Simplest Possible Self-Contained Example Showing the Bug

Used an external postgresql DB, not sure whether SQLite supports unique constraints?

```rb
# frozen_string_literal: true

require "bundler"
Bundler.setup

require "sequel"

DB = Sequel.connect ENV["DATABASE_URL"]

Sequel.extension :migration

Sequel.migration do
  up do
    create_table :albums do
      primary_key :id
      column :title, :text, null: false, unique: true
      column :type, :text, null: false
    end

    create_table :gold_albums do
      foreign_key :id, :albums
      primary_key [:id]
    end
  end
end.apply DB, :up

class Album < Sequel::Model
  plugin :auto_validations
  plugin :class_table_inheritance, key: :type
end

class GoldAlbum < Album
end

begin
  GoldAlbum.create title: nil
rescue Sequel::ValidationFailed
  puts $!.model.errors
end

GoldAlbum.create title: "Sports"

begin
  Album.create title: "Sports"
rescue Sequel::ValidationFailed
  puts $!.model.errors
end

begin
  GoldAlbum.create title: "Sports"
rescue Sequel::ValidationFailed
  puts $!.model.errors
end
```

### Full Backtrace of Exception (if any)

Output:

```
{:title=>["is not present"]}
{:title=>["is already taken"]}
...
/app/vendor/bundle/ruby/2.6.0/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:156:in `async_exec': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "albums_title_key" (Sequel::UniqueConstraintViolation)
DETAIL:  Key (title)=(Sports) already exists.
```

...what I expected is that `GoldAlbum.create` would behave like `Album.create` and output `{:title=>["is already taken"]}`

I _think_ the issue is here https://github.com/jeremyevans/sequel/blob/master/lib/sequel/plugins/auto_validations.rb#L173-L177

If I'm following that right then I think the `@auto_validate_unique_columns` variable is inherited from the superclass (like the other auto-validation variables), but then may be overridden with `[]` because the unique constraint is not on the subclass table.

**Comment by jeremyevans** [comment]
The auto_validations plugin does not handle unique indexes for any model that uses a joined dataset, and CTI subclass models use joined datasets.  So this isn't a bug, this is expected behavior for auto_validations.

Simply inheriting the unique columns from the parent class only partially fixes the problem, since you still miss unique indexes in the subclass tables.

I don't want auto_validations depending on class_table_inheritance or vice-versa, so the best way to fix this would be to add a new plugin, and then set the unique columns correctly for all tables used in CTI subclass models.  I will add this to my todo list, but it might be a while before I can get to it. If you would like to see this in Sequel sooner, please submit a pull request that implements it.  Until then, you can address the issue by adding the necessary validations manually to the CTI subclass models.

**Comment by benalavi** [comment]
@jeremyevans awesome I appreciate the direction. I can work on a plugin for this behavior. Would you normally add caveats like this to the docs for auto validations as well?

> Simply inheriting the unique columns from the parent class only partially fixes the problem, since you still miss unique indexes in the subclass tables....I don't want auto_validations depending on class_table_inheritance or vice-versa...

Makes sense. One idea though: could it be solved by something as simple as?

```rb
@auto_validate_unique_columns ||= []
@auto_validate_unique_columns += db.indexes(table).select{|name, idx| idx[:unique] == true}.map{|name, idx| idx[:columns].length == 1 ? idx[:columns].first : idx[:columns]} if db.supports_index_parsing? && [Symbol, SQL::QualifiedIdentifier, SQL::Identifier, String].any?{|c| table.is_a?(c)}
```

...is that naive and would have unintended consequences? Or would that still be coupling the two plugins together too much? The nice thing being that it may avoid the current somewhat surprising behavior.

**Comment by jeremyevans** [comment]
Just adding indexes will break cases where the table for a model is changed, since it will keep unique indexes that are no longer valid.

Looking at the auto_validations plugin documentation, it doesn't specifically mention that unique validations are not added for models that use joined datasets.  I'll add that.
