### ISSUE TITLE
An disconnected DB object auto reconnect for next raw SQL querying

### ISSUE THREAD

**Issue by euxx** [jeremyevans/sequel#1751]
Just came across a situation like this:

```rb
# Step 1
DB = Sequel.connect('options')

# Step 2
DB['select * from items'].each do |row|
  p row
end
# It works as expected

# Step 3
DB.disconnect

# Step 4
DB['select * from items'].each do |row|
  p row
end
# It STILL works, did not expect it
```

It seems an disconnected DB object auto reconnect for next raw SQL querying, I didn't find this behavior in document.

So I want to make sure it's  a bug or designed like this?

**Comment by jeremyevans** [comment]
It is expected behavior.  Database#disconnect removes connections from the connection pool.  When a new connection is needed, since the connection pool is empty, Sequel creates a new connection at that time.  I think this would only seem like a bug to you if you are thinking that a Database object represents a single connection, when it does not.

As specified in the contribution guidelines, please ask questions about Sequel on the IRC channel or the Google Group.  Only use GitHub Issues if you are sure it is a bug in the library.

**Comment by euxx** [comment]
Thanks for the quick clarification.

> As specified in the contribution guidelines, please ask questions about Sequel on the IRC channel or the Google Group. Only use GitHub Issues if you are sure it is a bug in the library.

Ok, get it.
