### ISSUE TITLE
Creating a new constraint removes all old constraints

### ISSUE THREAD

**Issue by jubishop** [jeremyevans/sequel#1762]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

I create a table like this in my first migration:

```
Sequel.migration {
  change {
    create_table(:polls) {
      String :id, primary_key: true
      constraint(:id_min_length) { Sequel.char_length(id) >= 16 }

      String :title, null: false
      constraint(:title_not_empty) { Sequel.char_length(title) >= 1 }
      String :question, null: false
      constraint(:question_not_empty) { Sequel.char_length(question) >= 1 }
      Integer :expiration, null: false
    }
  }
}
 ```
 
then a few migrations later, I do :

```
Sequel.migration {
  change {
    alter_table(:polls) {
      add_column(:type, String, null: false, default: 'borda_single')
      add_constraint(:type_is_valid, type: %w[borda_single borda_split])
    }
  }
}
```

and now when i check my schema, all the original constraints are removed.  if i remove the `add_constraint` line, they survive just fine.

**Comment by jubishop** [comment]
i thought maybe my use of the word `type` was the problem, but i get the same results with any column name.

**Comment by jubishop** [comment]
if i put all the changes in one migration with no `alter_table` i also get a valid schema.  something specifically about the `add_constraint` call removes the other constraints.

**Comment by jeremyevans** [comment]
You don't state it, but I'm guessing you are using SQLite. SQLite doesn't support the alter table operation you are trying to do (`add_constraint`), and Sequel's emulation of table alteration support does not extend to CHECK constraints. SQLite does support adding a column to an existing table, which is why it works if you remove the `add_constraint` line. If you want this supported, you'll need to get SQLite to add support for adding constraints to an existing table.

**Comment by jubishop** [comment]
oh I am using sqlite.  ok thanks for the details!
