### ISSUE TITLE
Sequel.| (OR) uses AND instead

### ISSUE THREAD

**Issue by plujon** [jeremyevans/sequel#1776]
I thought that Sequel.| was for OR.  But apparently it uses AND

    irb> puts AccountStatus.where(Sequel.|({:id => 1, :name => '2'})).sql
    SELECT * FROM "account_statuses" WHERE (("id" = 1) AND ("name" = '2'))

Of course Sequel.or works as expected:

    irb> puts AccountStatus.where(Sequel.or({:id => 1, :name => '2'})).sql
    SELECT * FROM "account_statuses" WHERE (("id" = 1) OR ("name" = '2'))

If this is by design, perhaps the documentation in sql.rdoc should be updated to warn users that Sequel.| does not always mean "OR".

**Comment by tycooon** [comment]
The problem is you are passing just one argument to it (which is a Hash). If you change it to 2 arguments, it will work as you expect:

```ruby
> puts DB[:smth].where(Sequel.|({ a: 1 }, { b: 2 })).sql
SELECT * FROM "smth" WHERE (("a" = 1) OR ("b" = 2))
```

**Comment by tycooon** [comment]
However, it's not very obvious why `or` and `|` behave differently of course.

**Comment by jeremyevans** [comment]
This is by design.  `Sequel.or` is designed to take a single hash or array of pairs and combine the entries with `OR`.  `Sequel.|` is designed to take multiple arguments and combine them with `OR`.  Passing a single argument to `Sequel.|` is basically returning the argument converted to a Sequel expression, similar to calling `Sequel.expr` on the argument. I'll update the `sql.rdoc` file to be more clear as to the difference.
