### ISSUE TITLE
[Document Improvement] Add a working example for how to create a :json, :jsonb column.

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1804]
Hi, I want to add a new jsonb column to one of my table, but after check following document.

https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_json_rb.html
http://sequel.jeremyevans.net/rdoc/files/doc/postgresql_rdoc.html
https://github.com/jeremyevans/sequel/blob/master/doc/schema_modification.rdoc#column-types-

All about how to retrieve value from a exists json column, but, no clear clue about how to add
a json type column, in fact, i spend almost one hour to find out how to do this.

So, i consider we should improve document for this place,  i have to guess:

```rb
Sequel.migration do
  change do
    alter_table(:jin10_messages) do
      add_column :properties, :pg_json, default: {}
    end
  end
end

# PG::UndefinedObject: ERROR:  type "pg_json" does not exist
# LINE 1: ALTER TABLE "jin10_messages" ADD COLUMN "properties" pg_json

Sequel.migration do
  change do
    alter_table(:jin10_messages) do
      add_column :properties, :jsonb, default: {}
    end
  end
end

# Sequel::Error: The AND operator requires at least 1 argument

Sequel.migration do
  change do
    alter_table(:jin10_messages) do
      add_column :properties, :jsonb
    end
  end
end
```

And, finally, create this column success, but why we can not add a default value?

is there exists document for describe this? and following is a not a clear indicator
for specify this error.

Sequel::Error: The AND operator requires at least 1 argument

Thank you.

**Comment by zw963** [comment]
BTW： i add this new column with default value successful with following code:

```rb
Sequel.migration do
  change do
    alter_table(:jin10_messages) do
      add_column :properties, :jsonb, default: '{}'
    end
  end
end
```

I propose we should point out this default value usage, instead of raise strange Sequel::Error.

**Comment by adam12** [comment]
Provide the default as a String.

```ruby
add_column :properties, :json, default: "{}"
```

**Comment by jeremyevans** [comment]
https://github.com/jeremyevans/sequel/blob/master/doc/schema_modification.rdoc#column-types- already describes how to use database specific column types (see `In all other cases, Sequel uses the type specified verbatim:` and `you can use the column method and specify the types as the second argument`).

Your `:default=>{}` value isn't correct, because `:default` value is a Sequel expression, and `{}` is not a valid Sequel expression.  Hashes are treated as sets of conditions, and there is no reasonable generic interpretation of empty set conditions (cannot reasonably be treated as either true or false). If you do: `DB[:table].where(properties: {})`, it doesn't work either (models have the ability to do type conversion in the setter methods, but that isn't used below the model layer).  You could use the string form (`"{}"`), or you could use `Sequel.pg_jsonb({})` from the pg_json extension as the default value.

I don't consider this a bug in the documentation.  You cannot expect the documentation to describe every possible use case for every user.  However, I'll certainly consider pull requests to improve the documentation.
