### ISSUE TITLE
Why is there a different .ci.gemfile? The Gemfile doesn't work to run tests

### ISSUE THREAD

**Issue by eregon** [jeremyevans/sequel#1809]
I'm trying to run Sequel tests and I `bundle install` and then tried `bundle exec rake -T` but that gives:
```
$ bundle exec rake -T
/home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/rubygems_integration.rb:362:in `find_spec_for_exe': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/rubygems_integration.rb:390:in `activate_bin_path'
	from /home/eregon/.rubies/truffleruby-dev/bin/rake:42:in `<main>'
```

After some time I noticed it's a different Gemfile used in CI, `.ci.gemfile`, and so I need `export BUNDLE_GEMFILE=.ci.gemfile`.

Could we `mv .ci.gemfile` to `Gemfile` to make this much simpler?

**Comment by jeremyevans** [comment]
No.  I don't encourage the use of Gemfile for libraries.  It creates a lock file by default, which is a terrible idea for library development, IMO.  You can `gem install --development sequel` to get all necessary dependencies installed, then just run rake.

**Comment by eregon** [comment]
`rake` is not in the dev deps of sequel though, and I would definitely want to avoid to install sequel as a gem if I'm testing the version in-repo.
The lockfile can just be ignored in `.gitignore`, no?
I think that's what 99% of the gems do and it seems to just work fine and of course it's intuitive and simple to run their test suite.

**Comment by jeremyevans** [comment]
`rake` ships with Ruby, so you don't need to install it separately as a gem.

The problem with the lock file is that once it is created, you'll forever be testing with old versions of potential dependencies, instead of whatever the most recent versions of dependencies are available.  It makes it much more likely that issues in newer versions of dependencies will be missed.  For example, Rails 7 was released this week and broke one of Sequel's extensions that uses ActiveSupport::Duration.  If you were using a lockfile created before the Rails 7 release, you would not catch this issue, even if you had Rails 7 installed.

Just because having a Gemfile is a common pattern does not make it a good pattern.

**Comment by eregon** [comment]
I see, would you mind documenting `gem install --development sequel` + `rake spec` in CONTRIBUTING (or the README) for running the tests locally?

Could the CI just use that then, or the gemfile is needed for CI?

**Comment by jeremyevans** [comment]
Sure, that's a good idea, I added that.  The `.ci.gemfile` is needed for CI, since CI runs adapter tests, and the adapter gems aren't included in the gemspec, since they differ by platform, ruby version, and day of the year (seriously, read `.ci.gemfile`). `ci.gemfile` only include the adapters used by CI, not all adapters supported by Sequel.  In CI, the `.ci.gemfile.lock` isn't a problem, since there is a new repository checkout for every CI run.
