### ISSUE TITLE
Seuqel::Model.[] behaves strangely... maybe?

### ISSUE THREAD

**Issue by will** [jeremyevans/sequel#1897]
Hi, maybe this isn't a bug, espically if it's been the behavior for so long, but it was a big surprise to me and I've been (very happliy) using Sequel for a long time now.

If you do something like 

```ruby
# assume Album has an artist_id column, and the approripate many_to_one relation
artist = Artist.first
Album[artist: artist]
```

Sequel will generate the proper `select * from album where artist_id = $1 limit 1` query.

But if you do `Album[artist: nil]`, it wont use the knowledge of the defined relation to tack on `_id` and try a query like `select * from album where artist = $1` then the database will complain about the missing column. 

I could be missing something obvious, but this was pretty suprising to run into. If it's not a bug, then sorry for opeining the issue in advance.

**Comment by jeremyevans** [comment]
The current behavior is expected.  The filtering by association handling is only done for Sequel::Model values, arrays of Sequel::Model, or model datasets, it is not done for nil values, by design.

There was a recent comment that asked about a plugin for handling nil, which I said I'd be open to: https://github.com/jeremyevans/sequel/issues/1371#issuecomment-1194777751

**Comment by will** [comment]
Thank you!
