### ISSUE TITLE
Automatic primary key id assignment does not seem to happen using the mock database adapter

### ISSUE THREAD

**Issue by nelsnelson** [jeremyevans/sequel#2094]
### Complete Description of Issue

Using the mock database adapter, I expect the invocation of a Model class method `#create` to return an entity instance which has an automatically incremented primary key, so long as such a property is defined explicitly on the model class.

It appears that the automatic assignment of an id to a mocked serialized model entity instance is not happening.

I'd be surprised if I'm not simply doing something incorrectly, or missing the documentation which instructs me to use a particular option when connecting to the mock database.  Apologies in advance if I'm simply overlooking the appropriate method here.

Please see: https://github.com/nelsnelson/sequel-mock-specs/blob/main/README.md

### Simplest Possible Self-Contained Example Showing the Bug

Write-up project with test:

https://github.com/nelsnelson/sequel-mock-specs/blob/main/README.md

Failing spec test:

https://github.com/nelsnelson/sequel-mock-specs/blob/main/spec/example_spec.rb#L15

### Full Backtrace of Exception (if any)

No exception.  The id is nil after invoking the Model#create method.

### SQL Log (if any)

No SQL log.

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

### Sequel Version

5.74.0

**Comment by nelsnelson** [comment]
I tried to examine what the mock adapter does in the `Database#_execute` method, but it seemed to always only execute through the `block` conditional from the spec test referenced above, which seems unexpected to me.  I'd have expected `Database#execute_insert` to have been executed using the `meth: :autoid` option, but without any block.  Is it possible the block is somehow getting added accidentally?

**Comment by jeremyevans** [comment]
You probably want to set the the autoid and data to return:

```ruby
DB = Sequel.mock

ds = DB[:xs].with_fetch({:id=>1, :c1=>2, :c2=>3}).with_autoid(1)
ds.columns(:id, :c1, :c2)
class X < Sequel::Model(ds)
  set_primary_key :id
end
p X.create
# BEGIN
# INSERT INTO xs DEFAULT VALUES
# SELECT * FROM xs WHERE id = 1
# COMMIT
# => #<X @values={:id=>1, :c1=>2, :c2=>3}>
```

I'll confess that I did not look at your example or log, because they were not inlined.  So if the above doesn't help you solve the issue, please post the requested information inline.

Note that in the future, you probably want to open a Discussion instead of an Issue for questions regarding Sequel.  You should only open an Issue if you are fairly sure it is a bug.

**Comment by nelsnelson** [comment]
My apologies, @jeremyevans.  Thank you for your quick attention to this issue.  I will try to remember to open a discussion first instead of an issue in the future.  I checked the README for contribution guidelines, but I completely forgot to read the Contributing document -- I'm so embarrassed.

I have added the example inline as requested.

**Comment by jeremyevans** [comment]
Your example doesn't work because `with_fetch` and `with_autoid` return a new dataset, they do not modify the existing dataset.

You either need to set them before setting the model's dataset, as my example did, or use the Database#autoid= and Database#fetch= methods (which are used if the dataset does not have specific autoid and fetch settings.
