### ISSUE TITLE
Sequel fork safety

### ISSUE THREAD

**Issue by eregon** [jeremyevans/sequel#691]
Hello,

I experienced some trouble due to the connection socket being shared between two processes (caused by fork and "smart spawning" of Phusion Passenger).

I read a couple issues/threads on the list about it and looked the code of the default connection pool, ThreadedConnectionPool.

The commonly proposed solution to this problem is to disconnect just before/after fork with a server-dependent hook. I find it unsatisfying because it is brittle code depending on the environment and it would seem logical if Sequel was also fork-safe as it is thread-safe.

Concretely, ThreadedConnectionPool use `Thread.current` as the key for connections. Unfortunately, in MRI Thread.current is identical for the main thread across `fork`:

``` ruby
> fork { p Thread.current }
=> #<Thread:0x000001008d8e88 run>
> Thread.current
=> #<Thread:0x000001008d8e88 run>
```

While they are of course very different from the OS (two different native threads). This creates the sharing mentioned above.

I see possible two solutions:
- use the tuple `[pid, thread id]` instead of just `thread id` as key in `@allocated` and ensure there is no connection leaking after fork.
- detect `fork` by change of PID (since there seems to be no hook in standard Ruby before/after fork and decorating it might not be so nice). This could be done in `#hold` and do the disconnect/reconnect needed once.

What do you think?
I would really appreciate Sequel to be fork-safe by default.

**Comment by clord** [comment]
@jeremyevans, I find that this statement of yours is false:

> Adding a DB.disconnect call after your application is loaded but before it starts running/serving requests should never break code

We use postgres `LISTEN`/`NOTIFY` in a pretty standard way as a basic job dispatch mechanism. Specifically, we fork processes as the result of `NOTIFY`. Because of this issue (#691) and it's suggested fix (`disconnect` prior to fork) our job server has been occasionally missing `NOTIFY` events during the time between disconnect and the next iteration of `LISTEN` in the parent process. I would really prefer that the parent stays connected, and that the forked process reconnects to the server independently.  This took a lot of time to debug. It sounds like we might be able to disconnect in the forked child right off the bat instead of the suggestion that we do it in the parent prior to the fork, but I'm not sure this is documented behaviour, so we've enabled a slow-and-safe path until we can figure out what the situation is.

**Comment by jeremyevans** [comment]
@clord Without posting some example code, I can only guess what is happening.  First, some background:

If you are using the standard threaded connection pool, `DB.disconnect` does not disconnect connections that are in use, only connections in the pool that are available.  `DB.listen` checks out a connection from the pool during it's whole runtime, so such a connection should not be available in the pool, and therefore should not be disconnected while listen is running.

If you are using the single threaded pool, then it can delete in use connections, so if you are using that, you'd want to change to the default pool.

Note that in order not to miss notifications, you need to be using the `:loop` option in order to receive multiple notifications.  Otherwise, Sequel stops listening on the channel (UNLISTEN) before returning from `Database#listen`, as mentioned in the documentation for the method.  If you are not using the `:loop` option, but instead are looping manually doing something like:

```ruby
while true
  notification = DB.listen("channel")
  fork{do_something(notification)}
end
```

it's expected that you will lose notifications, and is unrelated to disconnection.  You would need to switch to:

```ruby
DB.listen("channel", :loop=>true) do |*notification|
  fork{do_something(notification)}
end
```

Note that you need to be careful to use `exit!` instead of `exit` in the forked processes, so that the parent socket connection won't be disconnected.

If you still think this is a bug and you can come up with a self contained reproducible example that shows the problem, please post it on the sequel-talk Google Group or open a new issue and I'll definitely see if I can help.

FWIW, the statement I made is not falsifiable, I said "should never break code", I didn't say "can never break code". :)  Not to mention that the statement was made about disconnection before running/serving requests, not about doing so at runtime in response to notifications.

**Comment by TiagoCardoso1983** [comment]
I'm with @jeremyevans on this one, and admire his patience in educating about this caveat.

FWIW this is documented everywhere when it concerns using fork-based app servers or Background job frameworks (Resque, Unicorn and Puma, besides Passenger), and usually for Active Record. Check Heroku documentation if you don't believe me. Everywhere there's a database involved and a fork, people warn against this sort of thing. This does not seem Sequel's problem to solve. If that, then ruby should clearly distinguish between the main thread and the "forked" main thread. But then again, should it? Fork is a Unix system feature. Ruby is not a Unix-only environment (it also supports windows). JRuby goes at extreme lengths to be able to fork, and I don't know any production case mixing fork with db pools. Even PostgreSQL recommends against it, as previously linked. 

The reason Passenger abstracts things away for Active Record is just based on popularity and common case (the main customer app is 95% almost always Rails-based), and to avoid yet-another-fork-db-connection-related-issue. They're not alone on that. Even Sidekiq takes care of checking connections back in after jobs are done **only** for Active Record (this is probably not documented in Sequel, and probably shouldn't). This does seem to be out-of-scope for Sequel.  

The only thing I'd argue is that Sequel stores are not fiber-safe, as they use Thread#[] as thread-local storage, but that's a completely different issue.

**Comment by clord** [comment]
@jeremyevans thanks, that was a very useful comment. It looks like the problem I'm seeing is that `unlisten` is being sent as part of `listen`, which you are saying is by design. 

The code I am porting from would look like this if possible:

``` ruby
begin
while running
  DB.listen("channel", timeout: 10)
  fork{do_something}
  update_state
  running = # Compute
end
ensure
  DB.unlisten "channel"
end
```

And the current ported version will unlisten via line 3 instead of in the `ensure`, probably because `update_state` is very fast usually so it was deemed ok to run in this manner... the assumption of which was the true cause of our bug anyway.

I suppose I could manually exec `LISTEN "Channel"` to avoid having the implicit `UNLISTEN` that `Database#listen` injects. It would be nice to have some api surface for raw listen/unlisten but I at least understand the situation better, thanks.

**Comment by jeremyevans** [comment]
Yes, unlistening on the channels before returning from listen is by design, and required if you want correct behavior with the following code:

```ruby
n1 = DB.listen("chan1")
n2 = DB.listen("chan2")
```

Without the unlisten, the second call to listen here could return a notification for chan1 even though you are only supposed to be listening on chan2.

You should be able to change your code to:

```ruby
running = true
DB.listen("channel", timeout: 10, :loop=>true) do |*notification|
  fork{do_something}
  update_state
  break unless running = # Compute
end
```

Note that if you want to just use the ruby-pg API, you can just use `DB.synchronize` to get access to the underlying PG::Connection object, and operate directly on that.

**Comment by clord** [comment]
I tried this:

``` ruby
DB.listen("channel", timeout: 10, loop:true) do
   puts "called"
end
```

and "called" is only printed in the event of an event on the channel, not in the case of a timeout. Looking at the code for `listen`:
```
            loop do
              t = timeout_block ? [timeout_block.call] : []
              conn.wait_for_notify(*t, &block)
              l.call(conn) if loop_call
            end
```
it's pretty clear that &block will only be called in `wait_for_notify`, which does not execute the block in the event of a timeout (which makes sense, it's used in the non-loop version too, where we would not expect it to run for a timeout). It does not seem like I have the API required to implement run-on-event-or-timeout in pure Sequel.

**Comment by jeremyevans** [comment]
Well, you can probably do it in pure sequel, but it would be uglier:

```ruby
called = false
DB.listen("channel", timeout: proc{called = false;10}, loop: proc{puts "not called" unless called}) do
   called = true
   puts "called"
end
```

**Comment by eregon** [comment]
@jeremyevans Hello!
What if Ruby added `at_fork`(:before/:after_parent/:after_child) hooks as in https://bugs.ruby-lang.org/issues/14921?
Would you consider automatically disconnecting Sequel connections in e.g., `at_fork(:before)` or `at_fork(:after_child)`?
That would prevent this issue form happening, make Sequel fork-safe, and have no performance cost on the fast path.

**Comment by jeremyevans** [comment]
@eregon I wouldn't do it automatically, as it would break code.  Let's say Sequel automatically uses `at_fork(:before)`.  Then if the user does something like:  `fork{exec('...')}`, you end up disconnecting connections in the current process for no reason. You still don't end up with fork safety in the case where a connection is currently checked out of the connection pool, since checked out connections would still be shared by the parent and child processes.

`at_fork(:after_child)` has all of the problems that `after_fork` has instead of `before_fork` for preforking webservers, it's definitely the wrong way to handle file descriptor sharing issues.  If you are concerned about preforking webservers, you should be disconnecting all connections before the fork, while no connections are checked out.

My reasoning hasn't changed in the last 5 years, it's still that trying to handle this automatically in Sequel  is a bad idea.  This should be handled in the application, as the application is the only place where it can be correctly handled.  Yes, such handling may not be automatic.  But I would rather no automatic handling than poor automatic handling, or automatic handling that works for a particular use case but deals poorly with other use cases.

**Comment by eregon** [comment]
@jeremyevans I am not convinced yet this cannot be done automatically and sensibly for the vast majority of realistic use cases (maybe even all). Could you elaborate on a few points?

> Let's say Sequel automatically uses at_fork(:before). Then if the user does something like: fork{exec('...')}, you end up disconnecting connections in the current process for no reason. 

Yes, but who does that? Ruby has many utilities for spawning subprocesses and I see very little good reason to fork+exec manually instead of `/spawn/system/popen/etc. Those later options won't trigger at_fork hooks.
And if there is something potentially touching the DB between the `fork` and `exec`, fork-safety would turn up very useful!

> You still don't end up with fork safety in the case where a connection is currently checked out of the connection pool, since checked out connections would still be shared by the parent and child processes.

Why not? If the parent closed (as in `close(2)`) the connection, there is no way the fork can ever access it, isn't it? So both will have to reestablish a new connection when they use the database, which seems perfectly safe.

> at_fork(:after_child) has all of the problems that after_fork has instead of before_fork for preforking webservers, it's definitely the wrong way to handle file descriptor sharing issues.

Could you link to some documentation about that?
I think that would:
1. be fork-safe
2. avoid disconnecting the parent uselessly
3. naturally deal with the issue by preventing the child to use the parent's connection

So intuitively this option sounds great to me. It's also similar to what Passenger uses to avoid file descriptor sharing automatically with ActiveRecord AFAIK. What are the drawbacks?

> If you are concerned about preforking webservers, you should be disconnecting all connections before the fork [manually, at the application level], while no connections are checked out.

If I use Sequel and some forking Ruby webserver (most do, and many by default), I'd like to have a sane situation *by default* and e.g., avoid end users of the website seeing database results of one another (and so leaking private information) due to unintentional connection sharing.
Yes, the problem is documented in a couple places, but it's also easy to miss it or forget about it, and it is fairly easy to get this issue with default settings.
More importantly, isn't good and safe behavior by default valuable?

> But I would rather no automatic handling than poor automatic handling, or automatic handling that works for a particular use case but deals poorly with other use cases.

Could you show realistic use cases where automatic fork-safety would be harmful? (using `at_fork(:after_child)`)

**Comment by jeremyevans** [comment]
> Yes, but who does that?

Not sure.  However, I'm guessing the following is not that uncommon, since it is the recommended way to support fork without breaking things in the parent:

```ruby
fork do
  something
  exit!
end
```

`at_fork(:before)` would break that use case and be unacceptable to me.

>Why not? If the parent closed (as in close(2)) the connection, there is no way the fork can ever access it, isn't it? So both will have to reestablish a new connection when they use the database, which seems perfectly safe.

You are talking about `close(2)` on the connection, but that's not what Sequel needs to do.  First `close(2)` would be called on a socket that Sequel generally doesn't deal with, that's a driver level issue.  Sequel would be calling `Database#disconnect`, which does a lot more than `close(2)`. Most disconnection code does not just `close(2)` a socket, it sends a proper protocol disconnect to the server over the connection first.

> Could you link to some documentation about that?
> I think at_fork(:after_child) { reconnect } would:

Sequel doesn't have `reconnect`, so I'm not sure what you mean.  If you mean by emptying the connection pool without disconnecting the connections in it, then you'll can run into problems when those objects are garbage collected and their finalizers are run potentially by multiple processes at the same time, often doing a protocol level disconnect on the socket before closing it.  If you mean actually disconnecting the connections and then creating new connections,, then you have the same issue, it just happens sooner.

> Could you show realistic use cases where automatic fork-safety would be harmful?

The burden is not on me to show it can cause no harm.  The burden is on the person who wants this added to prove doing so cannot cause harm.  I've already described possible ways this can be harmful.

This problem has a simple, manual solution with one line of code that causes no problems if used correctly.  That is preferable in my opinion to a more complex automatic case that will handle certain cases fine and break other cases.

As an analogy, there are many people using Sequel with multiple databases and model classes.  If they create a model class, Sequel doesn't attempt to look at all databases to try to find which one is the best fit for the model class (i.e. has the related table).  The burden is on the user to manually specify which database if the default database in use is not the desired one.

**Comment by eregon** [comment]
Thank you for the reply.

> `at_fork(:before)` would break that use case and be unacceptable to me.

To clarify, what would break exactly? The connection would be disconnected in the parent on `fork`, but I guess Sequel would automatically reconnect after. So what's the harm?

It's not ideal that on every `fork` the parent needs to disconnect (and reconnect later if the DB is accessed), I understand that.

> Sequel doesn't have reconnect, so I'm not sure what you mean. If you mean by emptying the connection pool without disconnecting the connections in it, then you'll can run into problems when those objects are garbage collected and their finalizers are run potentially by multiple processes at the same time, often doing a protocol level disconnect on the socket before closing it. If you mean actually disconnecting the connections and then creating new connections,, then you have the same issue, it just happens sooner.

This seems the meat of the issue, and the challenge is to do this correctly. It sounds fairly similar to `IO.for_fd`, on which `autoclose` must be disabled manually in Ruby (otherwise there is a double-close, or an early concurrent close() which is harmful).

So I think during the `at_fork(:after_child)` hook we'd need to empty/clear the connection pool, not send anything on those connections, but mark them (somewhat like `IO#autoclose=`) so indeed finalizers don't do anything, or alternatively just directly remove the finalizers on those objects.
Basically, we want to prevent these connections to communicate in any way with the database, since that would be done concurrently with the parent process.
Does that sound right? Are there any problems with this approach?

We should ideally also close the underlying file descriptors (and free native allocations for the connection pointer) as they won't be used. I'm not sure if e.g., `pg` has an API for that.
Reading a highly related thread of discussion shows I'm not alone to want that:
http://www.postgresql-archive.org/Detecting-libpq-connections-improperly-shared-via-fork-td5726553.html
> Daniel Farina-4: However, I would like to re-iterate that this is a very common 
problem, so it may be worth pausing to think about solving it. 
Whenever someone writes in saying "what's up with these strange SSL 
errors", generally the first question in response is "are you using 
unicorn?" (for Ruby, 'gunicorn' for Python).  The answer is almost 
invariably yes.  The remainder have renegotiation issues. 

One solution for postgres involves to close(2) the socket returned by [`PQsocket()`](https://www.postgresql.org/docs/9.5/static/libpq-status.html) and then call [`PQfinish()`](https://www.postgresql.org/docs/9.5/static/libpq-connect.html) to release resources without sending the termination sequence (as the socket is closed). [This user request](http://grokbase.com/t/postgresql/pgsql-hackers/00ckh16tyz/libpq-enhancement-for-multi-process-application
) specifically asks for exposing a single function doing that.

They also propose just not caring about the opened socket and native PGConn allocation. This seems safe and of course portable/independent of the specific database. After all, the parent process likely doesn't have a thousand open connections which could lead to file descriptors exhaustion or a significant memory leak (but often just 1 open connection I would expect).

---

FWIW it seems ActiveRecord deals with this problem directly nowadays, by checking `Process.pid` (which is fairly cheap as it's not a syscall but just a function call at least on Linux): https://github.com/rails/rails/blob/v5.2.0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L1041
Heroku seems to recommend to both disconnect in before_fork and reconnect in after_fork: https://devcenter.heroku.com/articles/forked-pg-connections
https://stackoverflow.com/questions/29918475/unicorn-do-i-need-to-disconnect-from-database-in-before-fork-block mentions there shouldn't be a need to disconnect in `before_fork`.

**Comment by jeremyevans** [comment]
> To clarify, what would break exactly? The connection would be disconnected in the parent on fork, but I guess Sequel would automatically reconnect after. So what's the harm?

Well...

> It's not ideal that on every fork the parent needs to disconnect (and reconnect later if the DB is accessed), I understand that.

I think you've answered your own question.  Correct use of `fork` followed by `exec` or `exit!` should not be penalized.

> This seems the meat of the issue, and the challenge is to do this correctly. It sounds fairly similar to IO.for_fd, on which autoclose must be disabled manually in Ruby (otherwise there is a double-close, or an early concurrent close() which is harmful).
>So I think during the at_fork(:after_child) hook we'd need to empty/clear the connection pool, not send anything on those connections, but mark them (somewhat like IO#autoclose=) so indeed finalizers don't do anything, or alternatively just directly remove the finalizers on those objects.
>Basically, we want to prevent these connections to communicate in any way with the database, since that would be done concurrently with the parent process.
>Does that sound right? Are there any problems with this approach?

Yes, it's way more complex than a single `Database#disconnect` call in the appropriate place in the application when using a pre-forking webserver and loading the application before forking.  Plus before Sequel could consider it, you would need to make sure all 13 database drivers that Sequel supports have a supported method for marking connections so they only `close(2)` the socket during GC finalization.  Even if that were done I'm not sure the cost/benefit of making this change would be worth it.

I'm sorry, but you and I just have a different philosophy regarding this.  You are willing to accept a large amount of complexity for an automated approach that benefits a particular case, without considering too much about other cases.  I think this is best solved by a simple manual solution in the particular case where it is needed, where a similar manual solution would be needed for most other libraries that use sockets.

I've been maintaining Sequel for 10 years.  Looking at the issues, there are only a handful that are related to this issue.  It's simply not a major issue for most Sequel users.  It's true that new users are occasionally bitten by it because they don't understand `fork` and didn't read the documentation for either Sequel or their webserver.  However, I think that vast majority of Sequel users have no problems with the status quo in regards to this issue, and adding complexity to handle it automatically is not worth it.

**Comment by eregon** [comment]
> You are willing to accept a large amount of complexity for an automated approach that benefits a particular case.

I'm trying to explore the available options. Agreed the approach of closing the socket but not communicating on the socket is tricky and needs special handling for each DB driver, sometimes not even exposed directly by the native DB library.

Probably removing the finalizer or disabling it is easier: we just need to know which object the finalizer is defined on (and use `ObjectSpace.undefine_finalizer`), or a way to mark the object as "should not be finalized". When the forked process exits, we can just let the OS release resources (the socket and native allocations for the connection).

From https://github.com/jeremyevans/sequel/issues/1431#issuecomment-406768094:
> In any case, yes, I think if you are using `fork`, you should know to use `exec` or `exit!` if you want to avoid the issue.

Could preforking webservers use this? Specifically, since they fork, they would need to ensure all the forked processes end with `exit!` so finalizers & `at_exit` hooks are not run multiple times if some finalizers & `at_exit` hooks were defined in the parent process.

That would avoid the double disconnect, but of course something else would still be needed so the connection is not reused in multiple processes.
A fairly simple
```ruby
at_fork(:after_child) {
  Sequel::KEEP_ALIVE = DB.pool.available_connections.dup
  DB.pool.available_connections.clear
}
```
should be enough for that (if we assume the webserver uses `exit!`).

Alternatively, "a new `object_id`-like identifier which changes across fork: `Thread.current.thread_id`" [as mentioned by Eric Wong](https://bugs.ruby-lang.org/issues/5446#note-30) could help to make this slightly easier than using a `[PID, Thread]` tuple (which I guess is the most common approach currently for fork+thread safety).

**Comment by jeremyevans** [comment]
> Probably removing the finalizer or disabling it is easier: we just need to know which object the finalizer is defined on (and use ObjectSpace.undefine_finalizer), or a way to mark the object as "should not be finalized". When the forked process exits, we can just let the OS release resources (the socket and native allocations for the connection).

I would not even consider messing with the internal state of the connection objects to try to implement this.  A prerequisite for support in Sequel would be support in the drivers.  That's a necessary condition, but not a sufficient one.

> Could preforking webservers use this? 

I don't think they could do so automatically or by default.  Calling `exit!` instead of exiting normally can break a whole number of things, and should only be used in specific circumstances.  Consider the case where users are currently using preforking webservers correctly by calling `Database#disconnect` in the parent process before forking worker processes, but then using `at_exit` in each worker for some processing.  If the preforking webservers started calling `exit!` instead of exiting normally, they break that case.

> Alternatively, "a new object_id-like identifier which changes across fork: Thread.current.thread_id" as mentioned by Eric Wong could help to make this slightly easier than using a [PID, Thread] tuple (which I guess is the most common approach currently for fork+thread safety).

That would only affect the case of currently checked out connections on the thread that forks, which would end up like currently checked out connections on threads other than the one that forked.  It doesn't affect connections that are not currently checked out, which would still be available to be checked out in both the parent and child.

**Comment by fertobar** [comment]
I think I having the same issue with Puma, combined with ELB and pgbouncer.
ELB has a max idle timeout and close the connection after N seconds (default 100 s, max 4000 s)
Then, when there is a peak of traffic new threads are raised and I can see:
`Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. 
`
that is raised because ELB close connection due idle timeout.

I have **connection_validation_timeout** but seems was ignored, surelly due the issue you mention.

The unique that helped was **connection_expiration_timeout** less than ELB idle timeout. The unique issue is that refresh of connections is expensive if the period of time is small.

Maybe is a Puma issue, but there is some way to send some kind of TCP keep alive each n seconds,  different way to configure sequel settings, or prevent to avoid to get the _Sequel::DatabaseDisconnectError_ 
without need to hack Puma?

Any help is appreciated.

**Comment by janko-m** [comment]
@boazsegev Sequel stores each `Sequel::Database` object created by `Sequel.connect` in the `Sequel::DATABASES` array. That's how it's able to infer the default database when using models, it just takes the first item from that array.

So you should be able to disconnect all Sequel database connections with:

```rb
Sequel.synchronize do
  Sequel::DATABASES.each { |database| database.disconnect }
end
```

**Comment by boazsegev** [comment]
@janko-m , Thanks!

I [committed a patch](https://github.com/boazsegev/iodine/blob/2e058b29865e77897b88bc0f9a225d575740b3ed/lib/iodine.rb#L119-L134) to automate server `fork`-ing with iodine and Sequel. This will be part of the next iodine release 👍🏻🎉

... unless you have objections... **I wouldn't want to introduce a default behavior that the Sequel team disapproves of**...?

Kindly,
   B.

P.S.

I think adding the code to the servers (or frameworks) will make it easier for developers... after all, by the time developers use Rack or lower level features, they should already know about the issues related to `fork`.

**Comment by jeremyevans** [comment]
@boazsegev The patch looks good, except that you should drop the usage of `Sequel.synchronize`.

**Comment by boazsegev** [comment]
@jeremyevans Thanks!
