### ISSUE TITLE
Timestamps plugin - allow to manually set updated_at

### ISSUE THREAD

**Issue by elado** [jeremyevans/sequel#927]
Currently, with `plugin :timestamps, update_on_create: true` on my model, I can't manually update `updated_at`.

```ruby
p = Post[1]
p.updated_at # => 2015-01-06 02:17:08 UTC
p.updated_at = 3.days.ago.utc # => 2015-01-03 02:17:18 UTC
p.save

p.reload
p.updated_at # => 2015-01-06 02:17:24 UTC
```

**Comment by jeremyevans** [comment]
This is expected.  The plugin is designed to set `updated_at` to the current time, so it overrides any existing value.  If you must override `updated_at`, you'll have to drop down to the dataset level: `p.this.update(:updated_at=>3.days.ago.utc)`

**Comment by elado** [comment]
Why not allowing this feature? As in, keeping a flag whether it was set and skipping the update to current time. It seems natural functionality. AR supports it afaik.

**Comment by jeremyevans** [comment]
Well, this isn't a venue for new feature requests, only for bug reports, as stated in the contribution guidelines.

We could probably use an approach that tried to detect if the `updated_at` column  had been changed (using `changed_columns`) and only updating it if it hadn't been changed.  I suppose I could consider an option to the plugin to do that assuming there was community support for it.  If you'd like the feature to be considered, please post on the sequel-talk Google Group and try to gather community support for it.

Personally, I consider such things to be abusing the point of the timestamps plugin.  Also, it opens up security issues if developers aren't being careful in their mass assignment, since it can allow users to update timestamps when the developer did not expect them to be able to.
