### ISSUE TITLE
issue with table column named "model"

### ISSUE THREAD

**Issue by anazar** [jeremyevans/sequel#929]
I have a vehicle table with a column that is unfortunately named "model"  -- I'm unable to change this column name since the database is used by a number of other applications.

This seems to be causing issues w/ validation, saving, and a number of other things due to the conflict with the already existing model method.  

This was actually not an issue in activerecord, but since moving over to sequel I'm unable to get past this issue.

Is there a solution or workaround?

**Comment by jeremyevans** [comment]
Well, it's just like if you have a column called `save`, it conflicts with an existing method, and most Sequel internal methods call the method to get the value.

You should be able to work around each issue, but a simpler way to solve it may be to fudge the column information:

```ruby
DB.create_table(:bs){primary_key :id; String :model}

class B < Sequel::Model
  def self.get_db_schema(*)
     res = super
     columns.map!{|c| c == :model ? :model_name : c}
     db_schema[:model_name] = db_schema[:model]
     res
  end
  set_dataset dataset
  def_column_alias :model_name, :model
end

B.create(:model_name=>'Foo')
```

You'll want to skip any autovalidations for the model, and validate manually.  While the above works, there may be issues in other areas.

I think this issue is fixable by changing Sequel such that instead of using `send(:column)` to get a column value, it calls `get_column_value(:column)`, where `get_column_value` would just be an alias to `send`.  That way, you could just override a method to change the behavior.  That's a pretty invasive change, but I think it's the best way to go.  If it is an alias and not a new method, there should be no performance hit for users who are not overriding it.  I'll try to get that in before the next release.

**Comment by jeremyevans** [comment]
Also, look at the column_conflicts plugin I just committed, which should hopefully take care of your use case automatically.

**Comment by jrgns** [comment]
Nice. When is this being released?

**Comment by jeremyevans** [comment]
Per usual, Sequel releases around the first of every month.

**Comment by jrgns** [comment]
Ah, thanx
