### ISSUE TITLE
Dataset#intersect differing results with identical queries

### ISSUE THREAD

**Issue by pepijn** [jeremyevans/sequel#934]
First, create identical datasets.

```ruby
[20] pry(main)> q1 = db[:users].select(:wallet_id)
=> #<Sequel::Postgres::Dataset: "SELECT \"wallet_id\" FROM \"users\"">
[21] pry(main)> q2 = db["SELECT wallet_id FROM users"]
=> #<Sequel::Postgres::Dataset: "SELECT wallet_id FROM users">
```

The datasets are equal. Now let's create a dataset to intersect.

```ruby
[24] pry(main)> deposited_users = db["SELECT DISTINCT receiver_id AS wallet_id FROM transactions WHERE type = 'deposit'"]
=> #<Sequel::Postgres::Dataset: "SELECT DISTINCT receiver_id AS wallet_id FROM transactions WHERE type = 'deposit'">
```

This gives the expected result:

```ruby
[25] pry(main)> q1.intersect deposited_users
=> #<Sequel::Postgres::Dataset: "SELECT * FROM (SELECT \"wallet_id\" FROM \"users\" INTERSECT (SELECT DISTINCT receiver_id AS wallet_id FROM transactions WHERE type = 'deposit')) AS \"t1\"">
```

This one is unexpected though:

```ruby
[26] pry(main)> q2.intersect deposited_users
=> #<Sequel::Postgres::Dataset: "SELECT * FROM (SELECT wallet_id FROM users) AS \"t1\"">
```

This seems like a bug to me.

**Comment by jeremyevans** [comment]
In general, this type of behavior is expected.  Any time you provide raw SQL to Sequel, you basically shouldn't expect to be able to use the DSL to modify it, unless you call `from_self` (which will use a subselect for the query).

This case is a little different though, because Sequel already tries to automatically use `from_self` for `INTERSECT`/`EXCEPT`/`UNION`, because that is necessary to handle `ORDER BY` and `LIMIT` correctly, so it's fairly simple to do that for raw SQL as well.  So I'll add a patch to handle this particular case.

**Comment by pepijn** [comment]
Great, thanks! :+1:
