### ISSUE TITLE
Where do extra values go after calling an eager_graphed #all ?

### ISSUE THREAD

**Issue by contentfree** [jeremyevans/sequel#935]
For example, given an Article that has an Author and a Category, I want to get the count of articles by an author and a category. In SQL, I'd do this by selecting all from articles, authors and categories (to eager load), left joining authors and categories, grouping by author and category and appending a count column.

In Sequel, this looks something like:
````
Article.eager_graph(:author, :category)
       .group(:author_id, :category_id)
       .select_more(Sequel.function(:count, :id).as(:article_count))
````

This generates the correct SQL, however, after calling `#all` and building the graph nicely, the `article_count` field is nowhere to be found. I expected it to be somewhere on the Article (even if I have to get to it with `[]`). 

So where'd it go?

**Comment by jeremyevans** [comment]
You can't use `select_more` or similar methods when graphing, you need to use `add_graph_aliases` so that Sequel knows in which object to place the columns.

Also, using `eager_graph` with `group` seems odd.  If you just want to join and not eager load, use `association_left_join`.

If all you want is a count of articles by author and category, and you don't need any information from the author's or categories tables, you shouldn't even need to join.  For example, the following should give you a hash keyed by [article_id, category_id] with a count of the number of articles.

```ruby
Article.naked
   .select_group(:author_id, :category_id)
   .select_append(Sequel.function(:count, :id).as(:article_count)).
   .to_hash([:author_id, :category_id], :article_count)
```

I have the feeling that may not be exactly what you want, though.  If it isn't, you should probably post more details on the sequel-talk Google Group.

Note that Github Issues should only be used for reporting bugs in Sequel, questions on how to use Sequel should go on the Google Group or IRC, as stated in the contribution guidelines.

**Comment by contentfree** [comment]
`add_graph_aliases` results in the same thing: `article_count` is in the resulting hash, but once `#all` is called then its value goes a-missin'. I'm on IRC now and will move discussion there.

**Comment by art-solopov** [comment]
Have you found how to make the additional columns work?

**Comment by art-solopov** [comment]
Okay, I understand now. `association_left_join` with `select_more` works. The value is fetchable via `[]`.
