### ISSUE TITLE
pg_json plugin: unable to store typecasted JSONArray to Array in JSON data column

### ISSUE THREAD

**Issue by JeanMertz** [jeremyevans/sequel#937]
```
sequel (4.11.0)
postgres (PostgreSQL) 9.2.8
ruby 2.0.0p598 (2014-11-13) [x86_64-darwin14.0.0]
```

unexpected:

```ruby
historical_pricing.class
=> Sequel::Postgres::JSONArray

prices = historical_pricing.to_a
=> []

prices.class
=> Array

self.historical_pricing = (prices << 100)
=> [100]
```

```sql
UPDATE "tiers" SET "updated_at" = '2015-01-21 13:26:55.921358+0100' WHERE ("id" = 5)
```

*note that I left off some unrelated updated attributes in the above example*

workaround (see `prices = [*historical_pricing]`):

```ruby
historical_pricing.class
=> Sequel::Postgres::JSONArray

prices = [*historical_pricing]
=> []

prices.class
=> Array

self.historical_pricing = (prices << 100)
=> [100]
```

```sql
UPDATE "tiers" SET "updated_at" = '2015-01-21 13:28:36.069390+0100', "historical_pricing" = '[100]'::json WHERE ("id" = 5)
```

**Comment by jeremyevans** [comment]
This is expected behavior, as `update`/`save_changes` only updates columns that it knows have changed.  In the first example, you are mutating the array, so it doesn't know the value has changed.  In the second example, you are assigning a new array, so it knows the value has changed.  If you want to mutate values, you have a few options:

1) Use `modified!(:historical_pricing)` to explicitly set that the column has been modified.
2) Use the `modification_detection` plugin to automatically check for modifications.
3) Use `save` instead of `update`/`save_changes`.
