### ISSUE TITLE
Sequel can't escape \x00 in queries to SQLite

### ISSUE THREAD

**Issue by kartenis** [jeremyevans/sequel#953]
This may have some security implications, but I am not aware of those.

It doesn't matter if I use `String`, or `String type: :text`, or `File`, the exception always gets raised. 

    require "sequel"
    require "fileutils"
    
    FileUtils.rm_f("test.db")
    
    DB = Sequel.connect("sqlite://test.db")
    
    DB.create_table :test do
      String :test, type: :text
    end
    
    DB[:test] << {test: "\x00"}

**Comment by jeremyevans** [comment]
This is expected, you can't use ASCII NUL characters in text/varchar fields in most databases.  If you want to store ASCII NUL in a field, you need to use a blob: `DB[:test] << {test: Sequel.blob("\x00")}`

If you think this may have security implications, you should report it upstream to the ruby-sqlite3 developers, as they would need to update `::SQLite3::Database.quote` to handle such characters specially.  I don't think it has security implications, since all queries using ASCII NUL would be invalid, and SQLite correctly raises an exception for such queries.
