### ISSUE TITLE
Prepared statement with limit and offsets

### ISSUE THREAD

**Issue by ramarnat** [jeremyevans/sequel#976]
I have a process that splits up a large table extract among different threads using limit and offset. Is it possible to use prepared statements to use the limit and offsets as variables? I can use ds.sql and substitute the `LIMIT var`, but the limit/offset sql could be different depending on the database in question. 

Is there a more elegant way of doing this in Sequel?

**Comment by jeremyevans** [comment]
I can't guarantee this works on all databases, since I'm not sure all databases support bound variables for limit/offset, but I tested on SQLite and it works:

```ruby
ps = DB[:table].limit(:$limit, :$offset).prepare(:select, :lo)
ps.call(:limit=>1, :offset=>2)
ps.call(:limit=>2, :offset=>1)
```

If the database doesn't support that, you could use a placeholder literalizer:

```ruby
loader = Sequel::Dataset::PlaceholderLiteralizer.loader(DB[:table]) do |pl, ds|
  ds.limit(pl.arg, pl.arg)
end
loader.all(1, 2)
loader.all(2, 1) 
```

Note that as mentioned in the contribution guidelines, questions about how to use Sequel should be asked on IRC or the Google Group.  GitHub Issues should only be used for bug reports.
