### ISSUE TITLE
Allow ruby defaults on Postgres array columns

### ISSUE THREAD

**Issue by schwern** [jeremyevans/sequel#989]
It would be nice if one could specify defaults on Postgres array columns as Ruby arrays.

    column :titles, 'varchar[]', default: []

This solves two problems.  First, `default: []` is currently ignored with no warning.  The column will wind up with no default.

Second, if it has a not null constraint auto_validations will not see it has a default and do a presence validation.  auto_validations looks only for a ruby_default (possibly a bug).  This makes it difficult to use auto_validations with Postgres arrays.

I'd implement it, but I'm not sure where it would go.

**Comment by jeremyevans** [comment]
This isn't a bug.  When you do:

```ruby
column :titles, 'varchar[]', default: []
```

Sequel runs the SQL:

```sql
CREATE TABLE "a" ("titles" varchar[] DEFAULT (NULL))
```

So it is not ignoring the `:default` option.  Ruby arrays are literalized as SQL value lists by default, and the empty array is literalized as the value list `(NULL)`, which results in a `NULL` default for the column.

If you want to use an empty PostgreSQL array as the default, do `:default => Sequel.pg_array([])`.  This requires you load the pg_array extension into the Database object. I think if you fix your `:default` option value, your problem will be solved.

**Comment by schwern** [comment]
I do not get that behavior.  This code...

    column :address, 'varchar[]', default: []

Produces this SQL

    address character varying[]

Furthermore, I get an error if I try to use an array with elements in it.

      column :address, 'varchar[]',     default: ["foo", "bar"]

Produces...

    "address" varchar[] DEFAULT ('foo', 'bar')

Which errors.

    Sequel::DatabaseError: PG::DatatypeMismatch: ERROR:  column "address" is of type character varying[] but default expression is of type record

I am using these extensions.

    Sequel::Model.db.extension :pg_array, :pagination, :pg_json, :pg_location

I do not agree that it should be null.  `[]` and `nil` are not the same in Ruby.  `{}` and `NULL` are not the same in a PG array column.  If I meant to pass NULL I will use nil or just no default.

From a functional perspective, this leaves no way to have an empty array as a default for a PG array column.

PG array columns should either turn Ruby arrays into PG arrays, or they should error when they see an array.  The current behavior seems like its just the default behavior for scalar columns.

**Comment by jeremyevans** [comment]
This code...

```ruby
column :address, 'varchar[]', default: []
```

Produces this SQL:

```sql
CREATE TABLE "a" ("address" varchar[] DEFAULT (NULL))
```

If you don't believe me, look at the SQL log.  Also, there is no way Sequel would change `varchar[]` into `character varying[]`, you must be looking at the output of some PostgreSQL tool, not at the SQL that Sequel is actually sending.

As I explained earlier, ruby arrays are literalized as SQL value lists, not as PostgreSQL arrays.  If you want to use a PostgreSQL array, you have to specifically create a PostgreSQL array object using `Sequel.pg_array`.  It doesn't make sense to treat plain ruby arrays as PostgreSQL arrays when used as the `:default` option value, since that would give users the false idea that using plain ruby arrays as PostgreSQL arrays would work in other places.  I already gave an example above if you want to use an empty array as a default for a column.

Yes, the code you have to write in this case is a little more verbose, but it is consistent with PostgreSQL array usage in the rest of Sequel.  I prefer that to a little less verbose code but inconsistent behavior.

**Comment by schwern** [comment]
I was looking at `db/structure.sql`, which I now see is a dump. I see your behavior from the migration output, so we're now seeing the same things.  Good.

I noticed another problem with the idea that `default: []` is the same as `default: nil`.  This...

    column :address, 'varchar[]', null: false, default: []

Comes out as this bit of absurdity.

    "address" varchar[] DEFAULT (NULL) NOT NULL

> that would give users the false idea that using plain ruby arrays as PostgreSQL arrays would work in other places.

If I understand correctly, you want PG/Ruby array integration to be an all-or-nothing thing?  I'm ok with that.  I don't have enough experience with Sequel do all the necessary patching, maybe later.

I do agree that the user should not be mislead.  To that end, how about if I patch things up so a Ruby array default on a PG array column is an error?  Perhaps the error instructs the user to use Sequel.pg_array instead?  It's much better than being silently translated into `default(NULL)`, which is quite unexpected, or into a string with no hope of working.  That'll close this little loophole tricking new users (like me) into thinking Ruby and PG arrays are interchangeable.

Sound good?  I'll work up a pull request.

**Comment by jeremyevans** [comment]
I'm generally against attempting to check against all possible ways to misuse the library.  If you are going to specifically check for a ruby array, you might as well just convert the value to a PostgreSQL array object.  I've expressed that I think that is a bad idea, as it leads the user into thinking that array values are generally usable as PostgreSQL arrays.

However, since an SQL value list generally does not make sense as a default value, I guess there is no harm in overriding `Database#column_definition_default_sql` in the pg_array extension to automatically convert ruby arrays to PostgreSQL arrays objects.  So I'll reopen this issue.  If you have some time to work on a patch for this, that would be great, otherwise I'll try to commit a fix in a couple days.

Thanks for your patience and tenacity in trying to improve Sequel. :)
