### ISSUE TITLE
Restricted mass-assignments use generic Sequel::Error exception.

### ISSUE THREAD

**Issue by askreet** [jeremyevans/sequel#994]
I'm currently using Sequel in a Sinatra project and was planning to use the `set_allowed_columns` so that my routes which manipulate tables cannot override internal fields.  Ideally, I'd just use a sinatra error handler and return a 400-class response, but it seems the `resticted_set` method raises the same generic `Sequel::Error` you'd see if MySQL were unavailable, for example.

I'm wondering if you're open to some more specific error classes that subclass `Sequel::Error` (to maintain backwards compatibility, such as `Sequel::Model::RestrictedFieldError`.

I'm willing to write the patch and submit a PR, just wanted to get a :+1:.

Thanks!

**Comment by jeremyevans** [comment]
I'm OK with this idea, but we'll need to come up with a more accurate class name (maybe just `Sequel::Model::MassAssignmentError`).  Note that you can already separate errors due to the database being unavailable (`Sequel::DatabaseConnectionError`, `Sequel::DatabaseDisconnectError`) or other database errors (`Sequel::DatabaseError`) from errors raised by Sequel itself.

**Comment by jeremyevans** [comment]
I'll work on this shortly, since there is a related change I want to make to the exception class definitions.
