### ISSUE TITLE
ThreadedConnectionPool on sqlite memory database

### ISSUE THREAD

**Issue by ytti** [jeremyevans/sequel#996]
https://github.com/NLNOG/ring-sqa/blob/master/lib/ring/sqa/database.rb#L44

[45] pry(#<Ring::SQA::Database>)> @db.pool.available_connections.size
=> 2

[75] pry(#<Ring::SQA::Database>)> @db.pool.available_connections.first.total_changes
=> 8833
[76] pry(#<Ring::SQA::Database>)> @db.pool.available_connections.last.total_changes
=> 0

[82] pry(#<Ring::SQA::Database>)> @db.pool.available_connections.first.query 'select * from pings'
=> #<SQLite3::ResultSet:0x000000027e1100
...

[83] pry(#<Ring::SQA::Database>)> @db.pool.available_connections.last.query 'select * from pings'
SQLite3::SQLException: no such table: pings
from /var/lib/gems/1.9.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'

What is the expected situation? Is this misconfiguration?

**Comment by jeremyevans** [comment]
Can you post a self contained example showing how you ended up with 2 connections? I see the code sets the maximum connections to 1, though that shouldn't be necessary as Sequel's default maximum connections for an SQLite memory database is 1.

In any case, if you are ending up with more available connections than maximum connections, that's probably a bug.  The first step in fixing it is getting a small reproducible test case.  I can't reproduce even with something crazy like `10000.times{Thread.new{DB.synchronize{}}}`.

**Comment by ytti** [comment]
Sorry, I should have posted absolute URL. I changed the connection count from 3 to 1 yesterday, which does address the problem. So fault did not occur during 1.

So likely just pilot error and >1 connections in memory sqlite is non-sensical?

**Comment by jeremyevans** [comment]
Correct, each memory database on SQLite is restricted to a single connection, so if you allow more than 1 connection, that means that the database you use won't be shared.  There may be reasons to do that, but they are probably rare, which is why the default max connections is 1 for memory databases.  Maybe we should add something to the documentation (http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-sqlite) to make that more clear.

**Comment by ytti** [comment]
ACK. Thank you for your assistance.
